//! Crash-consistent workspace transaction for one proven source change set.
//!
//! POSIX cannot make several path renames instantaneously visible to processes
//! that ignore this workspace lock. Cooperating zttp writers are serialized,
//! and the journal guarantees recovery to one complete final state.

const std = @import("std");
const zts = @import("zts");
const TextBuffer = @import("text_buffer.zig").TextBuffer;
const change_set = @import("change_set.zig");
const workspace_snapshot = @import("workspace_snapshot.zig");
const aggregate_proof = @import("aggregate_proof.zig");
const common = @import("tools/common.zig");

const journal_schema_version: u32 = 1;

pub const FaultPoint = union(enum) {
    none,
    before_manifest_write,
    before_image_write: usize,
    before_receipt_write,
    after_prepared,
    before_stage_write: usize,
    after_applying,
    before_rename: usize,
    after_rename: usize,
    after_committed,
};

pub const CommitOptions = struct {
    fault: FaultPoint = .none,
    /// Exact aggregate UI/session receipt serialized before the first rename.
    /// Tests and lower-level callers may omit it and receive the compact
    /// transaction receipt generated by this module.
    receipt_json: ?[]const u8 = null,
};

pub const RecoveryFaultPoint = union(enum) {
    none,
    after_aborted_marker,
    before_transaction_directory_sync,
    before_source_file_sync: usize,
    before_source_directory_sync: usize,
    after_source_write: usize,
    after_candidate_verification,
    after_committed_marker,
    after_receipted_marker,
};

pub const RecoveryOptions = struct {
    fault: RecoveryFaultPoint = .none,
};

pub const CommitReceipt = struct {
    transaction_id: [64]u8,
    receipt_path: []u8,

    pub fn deinit(self: *CommitReceipt, allocator: std.mem.Allocator) void {
        allocator.free(self.receipt_path);
        self.* = undefined;
    }
};

/// A committed workspace receipt that has not yet been durably acknowledged by
/// its owning session journal. The transaction directory remains authoritative
/// until `markReceiptedLocked` succeeds.
pub const PendingReceipt = struct {
    transaction_id: [64]u8,
    json: []u8,

    pub fn deinit(self: *PendingReceipt, allocator: std.mem.Allocator) void {
        allocator.free(self.json);
        self.* = undefined;
    }
};

pub const WorkspaceLock = struct {
    allocator: std.mem.Allocator,
    fd: std.c.fd_t,
    path: []u8,

    pub fn acquire(allocator: std.mem.Allocator, workspace_root: []const u8) !WorkspaceLock {
        const canonical_workspace = try common.resolveInsideWorkspace(allocator, workspace_root, ".");
        defer allocator.free(canonical_workspace);
        const state_dir = try std.fs.path.resolve(allocator, &.{ canonical_workspace, ".zttp" });
        defer allocator.free(state_dir);
        var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
        defer io_backend.deinit();
        try std.Io.Dir.createDirPath(std.Io.Dir.cwd(), io_backend.io(), state_dir);
        try syncDirectory(allocator, state_dir);

        const path = try std.fs.path.resolve(allocator, &.{ state_dir, "change-set.lock" });
        errdefer allocator.free(path);
        const path_z = try allocator.dupeZ(u8, path);
        defer allocator.free(path_z);
        const fd = try std.posix.openatZ(
            std.posix.AT.FDCWD,
            path_z,
            .{ .ACCMODE = .WRONLY, .CREAT = true },
            0o600,
        );
        errdefer std.Io.Threaded.closeFd(fd);
        try lockExclusiveNonBlocking(fd);
        return .{ .allocator = allocator, .fd = fd, .path = path };
    }

    pub fn deinit(self: *WorkspaceLock) void {
        _ = std.c.flock(self.fd, std.posix.LOCK.UN);
        std.Io.Threaded.closeFd(self.fd);
        self.allocator.free(self.path);
        self.* = undefined;
    }
};

const ManifestChange = struct {
    path: []const u8,
    baseline_state: []const u8,
    baseline_sha256: []const u8,
    candidate_sha256: []const u8,
};

const Manifest = struct {
    schema_version: u32,
    proof_id: []const u8,
    workspace_root: []const u8,
    changes: []const ManifestChange,
};

pub fn commitLocked(
    allocator: std.mem.Allocator,
    lock: *const WorkspaceLock,
    prepared: *const change_set.PreparedChangeSet,
    snapshot: *const workspace_snapshot.Snapshot,
    proof: *const aggregate_proof.AggregateProof,
    options: CommitOptions,
) !CommitReceipt {
    _ = lock;
    try snapshot.recheck(allocator);

    const transaction_dir = try transactionPath(allocator, prepared.workspace_root, &proof.proof_id);
    defer allocator.free(transaction_dir);
    if (try pathExists(allocator, transaction_dir)) return error.TransactionAlreadyExists;
    const images_dir = try std.fs.path.resolve(allocator, &.{ transaction_dir, "images" });
    defer allocator.free(images_dir);
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    const io = io_backend.io();
    try std.Io.Dir.createDirPath(std.Io.Dir.cwd(), io, images_dir);

    if (options.fault == .before_manifest_write) return error.InjectedTransactionFailure;
    try writeManifest(allocator, transaction_dir, prepared, proof);
    try writeImages(allocator, transaction_dir, prepared, options.fault);
    if (options.fault == .before_receipt_write) return error.InjectedTransactionFailure;
    if (options.receipt_json) |receipt_json|
        try writeProvidedReceipt(allocator, transaction_dir, receipt_json, &proof.proof_id)
    else
        try writeReceipt(allocator, transaction_dir, prepared, proof);
    try writeMarker(allocator, transaction_dir, "prepared");
    try syncDirectory(allocator, transaction_dir);
    if (options.fault == .after_prepared) return error.InjectedTransactionFailure;

    try snapshot.recheck(allocator);
    const stages = try stageCandidates(allocator, prepared, &proof.proof_id, options.fault);
    defer {
        for (stages) |stage| {
            deleteFileIfPresent(allocator, stage) catch {};
            allocator.free(stage);
        }
        allocator.free(stages);
    }
    try snapshot.recheck(allocator);
    try writeMarker(allocator, transaction_dir, "applying");
    if (options.fault == .after_applying) return error.InjectedTransactionFailure;

    for (prepared.changes, stages, 0..) |change, stage, index| {
        switch (options.fault) {
            .before_rename => |fault_index| if (fault_index == index) return error.RenameFailure,
            else => {},
        }
        try renameAndSync(allocator, stage, change.resolved_path);
        try writeProgressMarker(allocator, transaction_dir, index);
        switch (options.fault) {
            .after_rename => |fault_index| if (fault_index == index) return error.InjectedTransactionFailure,
            else => {},
        }
    }
    try verifyCandidates(allocator, prepared);
    try writeMarker(allocator, transaction_dir, "committed");
    if (options.fault == .after_committed) return error.InjectedTransactionFailure;
    return .{
        .transaction_id = proof.proof_id,
        .receipt_path = try std.fs.path.resolve(allocator, &.{ transaction_dir, "receipt.json" }),
    };
}

/// Return committed receipts whose session acknowledgement is still missing.
/// Callers must first run `recoverAllLocked`: this scanner deliberately refuses
/// an incomplete transaction instead of guessing whether its source writes are
/// authoritative. Results are sorted by transaction id for deterministic
/// reconstruction.
pub fn pendingReceiptsLocked(
    allocator: std.mem.Allocator,
    lock: *const WorkspaceLock,
    workspace_root: []const u8,
) ![]PendingReceipt {
    _ = lock;
    const canonical_workspace = try common.resolveInsideWorkspace(allocator, workspace_root, ".");
    defer allocator.free(canonical_workspace);
    const root = try std.fs.path.resolve(allocator, &.{ canonical_workspace, ".zttp", "change-sets" });
    defer allocator.free(root);
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    const io = io_backend.io();
    var dir = std.Io.Dir.openDirAbsolute(io, root, .{ .iterate = true, .follow_symlinks = false }) catch |err| switch (err) {
        error.FileNotFound => return allocator.alloc(PendingReceipt, 0),
        else => return err,
    };
    defer dir.close(io);

    var transaction_ids: std.ArrayList([64]u8) = .empty;
    defer transaction_ids.deinit(allocator);
    var iterator = dir.iterate();
    while (try iterator.next(io)) |entry| {
        if (entry.kind != .directory or !isCanonicalProofId(entry.name)) return error.CorruptTransactionDirectory;
        const transaction_dir = try std.fs.path.resolve(allocator, &.{ root, entry.name });
        defer allocator.free(transaction_dir);
        if (!try markerPresent(allocator, transaction_dir, "prepared") or
            !try markerPresent(allocator, transaction_dir, "committed"))
        {
            return error.IncompleteTransactionRecovery;
        }
        if (try markerPresent(allocator, transaction_dir, "receipted")) continue;
        if (transaction_ids.items.len >= 1024) return error.TooManyPendingReceipts;
        var id: [64]u8 = undefined;
        @memcpy(&id, entry.name);
        try transaction_ids.append(allocator, id);
    }
    std.mem.sort([64]u8, transaction_ids.items, {}, struct {
        fn lessThan(_: void, left: [64]u8, right: [64]u8) bool {
            return std.mem.order(u8, &left, &right) == .lt;
        }
    }.lessThan);

    const receipts = try allocator.alloc(PendingReceipt, transaction_ids.items.len);
    var initialized: usize = 0;
    errdefer {
        for (receipts[0..initialized]) |*receipt| receipt.deinit(allocator);
        allocator.free(receipts);
    }
    for (transaction_ids.items, 0..) |id, index| {
        const transaction_dir = try std.fs.path.resolve(allocator, &.{ root, id[0..] });
        defer allocator.free(transaction_dir);
        try validateReceipt(allocator, transaction_dir, &id);
        const path = try std.fs.path.resolve(allocator, &.{ transaction_dir, "receipt.json" });
        defer allocator.free(path);
        receipts[index] = .{
            .transaction_id = id,
            .json = try readVerifiedFile(allocator, path, 64 * 1024 * 1024),
        };
        initialized += 1;
    }
    return receipts;
}

/// Durably records that the exact committed receipt is now present in its
/// owning persistence surface. This is idempotent and never removes the
/// workspace receipt.
pub fn markReceiptedLocked(
    allocator: std.mem.Allocator,
    lock: *const WorkspaceLock,
    workspace_root: []const u8,
    transaction_id: *const [64]u8,
) !void {
    return markReceiptedLockedWithOptions(
        allocator,
        lock,
        workspace_root,
        transaction_id,
        .{},
    );
}

/// Test-capable acknowledgement entry point. Default options are identical to
/// `markReceiptedLocked`; injected failures occur at named durable-effect
/// boundaries.
pub fn markReceiptedLockedWithOptions(
    allocator: std.mem.Allocator,
    lock: *const WorkspaceLock,
    workspace_root: []const u8,
    transaction_id: *const [64]u8,
    options: RecoveryOptions,
) !void {
    _ = lock;
    if (!isCanonicalProofId(transaction_id)) return error.InvalidTransactionId;
    const transaction_dir = try transactionPath(allocator, workspace_root, transaction_id);
    defer allocator.free(transaction_dir);
    if (!try markerPresent(allocator, transaction_dir, "prepared") or
        !try markerPresent(allocator, transaction_dir, "committed"))
    {
        return error.TransactionNotCommitted;
    }
    try validateReceipt(allocator, transaction_dir, transaction_id);
    if (!try markerPresent(allocator, transaction_dir, "receipted")) {
        try writeMarker(allocator, transaction_dir, "receipted");
        if (options.fault == .after_receipted_marker) return error.InjectedTransactionFailure;
    }
}

pub fn recoverAllLocked(
    allocator: std.mem.Allocator,
    lock: *const WorkspaceLock,
    workspace_root: []const u8,
) !usize {
    return recoverAllLockedWithOptions(allocator, lock, workspace_root, .{});
}

/// Test-capable recovery entry point. Default options are identical to
/// `recoverAllLocked`; injected failures occur at named durable-effect
/// boundaries.
pub fn recoverAllLockedWithOptions(
    allocator: std.mem.Allocator,
    lock: *const WorkspaceLock,
    workspace_root: []const u8,
    options: RecoveryOptions,
) !usize {
    _ = lock;
    const canonical_workspace = try common.resolveInsideWorkspace(allocator, workspace_root, ".");
    defer allocator.free(canonical_workspace);
    const root = try std.fs.path.resolve(allocator, &.{ canonical_workspace, ".zttp", "change-sets" });
    defer allocator.free(root);
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    const io = io_backend.io();
    var dir = std.Io.Dir.openDirAbsolute(io, root, .{ .iterate = true, .follow_symlinks = false }) catch |err| switch (err) {
        error.FileNotFound => return 0,
        else => return err,
    };
    defer dir.close(io);
    var recovered: usize = 0;
    var iterator = dir.iterate();
    while (try iterator.next(io)) |entry| {
        if (entry.kind != .directory or !isCanonicalProofId(entry.name)) return error.CorruptTransactionDirectory;
        const transaction_dir = try std.fs.path.resolve(allocator, &.{ root, entry.name });
        defer allocator.free(transaction_dir);
        if (try recoverOne(allocator, transaction_dir, options)) recovered += 1;
    }
    return recovered;
}

const PreparationState = enum { unprepared, prepared };

const RecoveryPhase = enum {
    unprepared,
    aborted,
    committed,
    prepared,
    applying,
};

const PreparedRecoveryPhase = enum { aborted, committed, prepared, applying };

const TargetObservation = struct {
    current: [32]u8,
    baseline: [32]u8,
    candidate: [32]u8,
};

const TargetAction = enum { keep_candidate, write_candidate };

const ApplyingPlan = struct {
    /// Borrows storage owned by the parsed manifest in `recoverOne`.
    manifest: Manifest,
    /// Owned by this plan.
    actions: []TargetAction,
};

const RecoveryPlan = union(RecoveryPhase) {
    unprepared: void,
    aborted: void,
    committed: void,
    prepared: void,
    applying: ApplyingPlan,

    fn deinit(self: *RecoveryPlan, allocator: std.mem.Allocator) void {
        switch (self.*) {
            .applying => |applying| allocator.free(applying.actions),
            .unprepared, .aborted, .committed, .prepared => {},
        }
        self.* = undefined;
    }
};

const ApplyingPlanner = struct {
    /// Borrows storage owned by the parsed manifest in `recoverOne`.
    manifest: Manifest,
    /// Owned until `finish` transfers it to a `RecoveryPlan`.
    actions: []TargetAction,
    next_index: usize,
};

const RecoveryPlanner = union(RecoveryPhase) {
    unprepared: void,
    aborted: void,
    committed: void,
    prepared: void,
    applying: ApplyingPlanner,

    fn observe(self: *RecoveryPlanner, observation: TargetObservation) !void {
        const applying = switch (self.*) {
            .applying => |*value| value,
            .unprepared, .aborted, .committed, .prepared => return error.RecoveryPhaseHasNoTargets,
        };
        if (applying.next_index >= applying.actions.len) return error.TooManyRecoveryObservations;
        const action: TargetAction = if (std.mem.eql(u8, &observation.current, &observation.candidate))
            .keep_candidate
        else if (std.mem.eql(u8, &observation.current, &observation.baseline))
            .write_candidate
        else
            return error.WorkspaceRecoveryConflict;
        applying.actions[applying.next_index] = action;
        applying.next_index += 1;
    }

    fn finish(self: *RecoveryPlanner) !RecoveryPlan {
        const plan: RecoveryPlan = switch (self.*) {
            .unprepared => .{ .unprepared = {} },
            .aborted => .{ .aborted = {} },
            .committed => .{ .committed = {} },
            .prepared => .{ .prepared = {} },
            .applying => |applying| blk: {
                if (applying.actions.len != applying.manifest.changes.len or
                    applying.next_index != applying.actions.len)
                {
                    return error.IncompleteRecoveryPlan;
                }
                break :blk .{ .applying = .{
                    .manifest = applying.manifest,
                    .actions = applying.actions,
                } };
            },
        };
        self.* = undefined;
        return plan;
    }

    fn deinit(self: *RecoveryPlanner, allocator: std.mem.Allocator) void {
        switch (self.*) {
            .applying => |applying| allocator.free(applying.actions),
            .unprepared, .aborted, .committed, .prepared => {},
        }
        self.* = undefined;
    }
};

fn observePreparation(allocator: std.mem.Allocator, transaction_dir: []const u8) !PreparationState {
    if (try markerPresent(allocator, transaction_dir, "prepared")) return .prepared;
    if (try markerPresent(allocator, transaction_dir, "applying") or
        try markerPresent(allocator, transaction_dir, "committed") or
        try markerPresent(allocator, transaction_dir, "receipted"))
    {
        return error.CorruptTransactionJournal;
    }
    return .unprepared;
}

fn observePreparedPhase(allocator: std.mem.Allocator, transaction_dir: []const u8) !PreparedRecoveryPhase {
    if (try markerPresent(allocator, transaction_dir, "aborted")) return .aborted;
    if (try markerPresent(allocator, transaction_dir, "committed")) return .committed;
    if (!try markerPresent(allocator, transaction_dir, "applying")) return .prepared;
    return .applying;
}

fn recoverOne(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    options: RecoveryOptions,
) !bool {
    if (try observePreparation(allocator, transaction_dir) == .unprepared) {
        var planner: RecoveryPlanner = .{ .unprepared = {} };
        var plan = try planner.finish();
        defer plan.deinit(allocator);
        return executeRecoveryPlan(allocator, transaction_dir, &plan, options);
    }

    var parsed = try loadManifest(allocator, transaction_dir);
    defer parsed.deinit();
    const manifest = parsed.value;
    try validateManifestAndImages(allocator, transaction_dir, manifest);
    const phase = try observePreparedPhase(allocator, transaction_dir);
    if (phase == .committed) {
        try validateReceipt(allocator, transaction_dir, manifest.proof_id);
    }

    var planner: RecoveryPlanner = switch (phase) {
        .aborted => .{ .aborted = {} },
        .committed => .{ .committed = {} },
        .prepared => .{ .prepared = {} },
        .applying => blk: {
            const actions = try allocator.alloc(TargetAction, manifest.changes.len);
            break :blk .{ .applying = .{
                .manifest = manifest,
                .actions = actions,
                .next_index = 0,
            } };
        },
    };
    var planner_owned = true;
    defer if (planner_owned) planner.deinit(allocator);

    if (phase == .applying) {
        for (manifest.changes) |change| {
            const current = try readStateDigest(allocator, change.path);
            const candidate = parseDigest(change.candidate_sha256) orelse return error.CorruptTransactionJournal;
            const baseline = parseDigest(change.baseline_sha256) orelse return error.CorruptTransactionJournal;
            try planner.observe(.{
                .current = current,
                .baseline = baseline,
                .candidate = candidate,
            });
        }
    }

    var plan = try planner.finish();
    planner_owned = false;
    defer plan.deinit(allocator);
    return executeRecoveryPlan(allocator, transaction_dir, &plan, options);
}

fn executeRecoveryPlan(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    plan: *const RecoveryPlan,
    options: RecoveryOptions,
) !bool {
    switch (plan.*) {
        .unprepared, .aborted => {
            try deleteTransactionDirectory(allocator, transaction_dir, options);
            return true;
        },
        .committed => return false,
        .prepared => {
            try writeMarker(allocator, transaction_dir, "aborted");
            if (options.fault == .after_aborted_marker) return error.InjectedTransactionFailure;
            try deleteTransactionDirectory(allocator, transaction_dir, options);
            return true;
        },
        .applying => |applying| {
            if (applying.actions.len != applying.manifest.changes.len)
                return error.IncompleteRecoveryPlan;
            for (applying.manifest.changes, applying.actions, 0..) |change, action, index| {
                switch (action) {
                    .keep_candidate => continue,
                    .write_candidate => {
                        const after_path = try imagePath(allocator, transaction_dir, index, "after");
                        defer allocator.free(after_path);
                        const after = try zts.file_io.readFile(allocator, after_path, change_set.max_file_bytes);
                        defer allocator.free(after);
                        try durableRecoveryWrite(allocator, change.path, after, index, options);
                        switch (options.fault) {
                            .after_source_write => |fault_index| if (fault_index == index)
                                return error.InjectedTransactionFailure,
                            else => {},
                        }
                    },
                }
            }
            try verifyManifestCandidates(allocator, applying.manifest);
            if (options.fault == .after_candidate_verification) return error.InjectedTransactionFailure;
            try writeMarker(allocator, transaction_dir, "committed");
            if (options.fault == .after_committed_marker) return error.InjectedTransactionFailure;
            return true;
        },
    }
}

fn durableRecoveryWrite(
    allocator: std.mem.Allocator,
    path: []const u8,
    bytes: []const u8,
    index: usize,
    options: RecoveryOptions,
) !void {
    const parent = std.fs.path.dirname(path) orelse return error.InvalidJournalPath;
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    try std.Io.Dir.createDirPath(std.Io.Dir.cwd(), io_backend.io(), parent);
    try zts.file_io.writeFile(allocator, path, bytes);
    switch (options.fault) {
        .before_source_file_sync => |fault_index| if (fault_index == index)
            return error.SyncFailure,
        else => {},
    }
    try syncFile(allocator, path);
    switch (options.fault) {
        .before_source_directory_sync => |fault_index| if (fault_index == index)
            return error.DirectorySyncFailure,
        else => {},
    }
    try syncDirectory(allocator, parent);
}

fn writeManifest(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    prepared: *const change_set.PreparedChangeSet,
    proof: *const aggregate_proof.AggregateProof,
) !void {
    const changes = try allocator.alloc(ManifestChange, prepared.changes.len);
    defer allocator.free(changes);
    const digest_strings = try allocator.alloc([64]u8, prepared.changes.len * 2);
    defer allocator.free(digest_strings);
    for (prepared.changes, 0..) |change, index| {
        const candidate_digest = change_set.digestBaseline(change.candidate);
        digest_strings[index * 2] = std.fmt.bytesToHex(change.baseline_sha256, .lower);
        digest_strings[index * 2 + 1] = std.fmt.bytesToHex(candidate_digest, .lower);
        changes[index] = .{
            .path = change.resolved_path,
            .baseline_state = if (change.baseline == .absent) "absent" else "present",
            .baseline_sha256 = &digest_strings[index * 2],
            .candidate_sha256 = &digest_strings[index * 2 + 1],
        };
    }
    var buffer = TextBuffer.init(allocator);
    defer buffer.deinit();
    try std.json.Stringify.value(Manifest{
        .schema_version = journal_schema_version,
        .proof_id = proof.proof_id[0..],
        .workspace_root = prepared.workspace_root,
        .changes = changes,
    }, .{}, buffer.writer());
    const path = try std.fs.path.resolve(allocator, &.{ transaction_dir, "manifest.json" });
    defer allocator.free(path);
    try durableWriteWithDigest(allocator, path, buffer.written());
}

fn writeImages(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    prepared: *const change_set.PreparedChangeSet,
    fault: FaultPoint,
) !void {
    for (prepared.changes, 0..) |change, index| {
        switch (fault) {
            .before_image_write => |fault_index| if (fault_index == index)
                return error.InjectedTransactionFailure,
            else => {},
        }
        if (change.baseline.bytes()) |before| {
            const before_path = try imagePath(allocator, transaction_dir, index, "before");
            defer allocator.free(before_path);
            try durableWrite(allocator, before_path, before);
        }
        const after_path = try imagePath(allocator, transaction_dir, index, "after");
        defer allocator.free(after_path);
        try durableWrite(allocator, after_path, change.candidate);
    }
}

fn writeReceipt(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    prepared: *const change_set.PreparedChangeSet,
    proof: *const aggregate_proof.AggregateProof,
) !void {
    var buffer = TextBuffer.init(allocator);
    defer buffer.deinit();
    const writer = buffer.writer();
    try writer.writeAll("{\"schema_version\":1,\"kind\":\"verified_change_set\",\"transaction_id\":");
    try std.json.Stringify.value(&proof.proof_id, .{}, writer);
    try writer.writeAll(",\"policy_hash\":");
    try std.json.Stringify.value(&proof.policy_hash, .{}, writer);
    try writer.writeAll(",\"read_set_digest\":");
    try std.json.Stringify.value(&proof.read_set_digest, .{}, writer);
    try writer.writeAll(",\"system_proven\":");
    try writer.writeAll(if (proof.system_proven) "true" else "false");
    try writer.writeAll(",\"changes\":[");
    for (prepared.changes, 0..) |change, index| {
        if (index > 0) try writer.writeByte(',');
        var candidate_digest: [32]u8 = undefined;
        std.crypto.hash.sha2.Sha256.hash(change.candidate, &candidate_digest, .{});
        const candidate_hex = std.fmt.bytesToHex(candidate_digest, .lower);
        try writer.writeAll("{\"file\":");
        try std.json.Stringify.value(change.authored_path, .{}, writer);
        try writer.writeAll(",\"baseline_state\":");
        try std.json.Stringify.value(if (change.baseline == .absent) "absent" else "present", .{}, writer);
        try writer.writeAll(",\"baseline_sha256\":");
        const baseline_hex = std.fmt.bytesToHex(change.baseline_sha256, .lower);
        try std.json.Stringify.value(&baseline_hex, .{}, writer);
        try writer.writeAll(",\"candidate_sha256\":");
        try std.json.Stringify.value(&candidate_hex, .{}, writer);
        try writer.writeAll("}");
    }
    try writer.writeAll("]}");
    const path = try std.fs.path.resolve(allocator, &.{ transaction_dir, "receipt.json" });
    defer allocator.free(path);
    try durableWriteWithDigest(allocator, path, buffer.written());
}

fn writeProvidedReceipt(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    receipt_json: []const u8,
    proof_id: *const [64]u8,
) !void {
    if (receipt_json.len == 0 or receipt_json.len > 64 * 1024 * 1024) return error.InvalidChangeSetReceipt;
    var parsed = std.json.parseFromSlice(std.json.Value, allocator, receipt_json, .{}) catch
        return error.InvalidChangeSetReceipt;
    defer parsed.deinit();
    if (parsed.value != .object) return error.InvalidChangeSetReceipt;
    const kind = parsed.value.object.get("kind") orelse return error.InvalidChangeSetReceipt;
    const transaction_id = parsed.value.object.get("transaction_id") orelse return error.InvalidChangeSetReceipt;
    if (kind != .string or transaction_id != .string or
        !std.mem.eql(u8, kind.string, "verified_change_set") or
        !std.mem.eql(u8, transaction_id.string, proof_id))
    {
        return error.InvalidChangeSetReceipt;
    }
    const path = try std.fs.path.resolve(allocator, &.{ transaction_dir, "receipt.json" });
    defer allocator.free(path);
    try durableWriteWithDigest(allocator, path, receipt_json);
}

fn stageCandidates(
    allocator: std.mem.Allocator,
    prepared: *const change_set.PreparedChangeSet,
    proof_id: *const [64]u8,
    fault: FaultPoint,
) ![][]u8 {
    const stages = try allocator.alloc([]u8, prepared.changes.len);
    var initialized: usize = 0;
    errdefer {
        for (stages[0..initialized]) |stage| {
            deleteFileIfPresent(allocator, stage) catch {};
            allocator.free(stage);
        }
        allocator.free(stages);
    }
    for (prepared.changes, 0..) |change, index| {
        const parent = std.fs.path.dirname(change.resolved_path) orelse return error.InvalidTargetPath;
        const base = std.fs.path.basename(change.resolved_path);
        const stage = try std.fmt.allocPrint(allocator, "{s}/.{s}.zttp-{s}.stage", .{ parent, base, proof_id[0..16] });
        errdefer allocator.free(stage);
        if (try pathExists(allocator, stage)) return error.StaleStageFile;
        switch (fault) {
            .before_stage_write => |fault_index| if (fault_index == index)
                return error.InjectedTransactionFailure,
            else => {},
        }
        try durableWrite(allocator, stage, change.candidate);
        stages[index] = stage;
        initialized += 1;
    }
    return stages;
}

fn verifyCandidates(allocator: std.mem.Allocator, prepared: *const change_set.PreparedChangeSet) !void {
    for (prepared.changes) |change| {
        const current = try zts.file_io.readFile(allocator, change.resolved_path, change_set.max_file_bytes);
        defer allocator.free(current);
        if (!std.mem.eql(u8, current, change.candidate)) return error.PostCommitVerificationFailed;
    }
}

fn verifyManifestCandidates(allocator: std.mem.Allocator, manifest: Manifest) !void {
    for (manifest.changes) |change| {
        const expected = parseDigest(change.candidate_sha256) orelse return error.CorruptTransactionJournal;
        const current = try readStateDigest(allocator, change.path);
        if (!std.mem.eql(u8, &current, &expected)) return error.PostCommitVerificationFailed;
    }
}

fn durableWrite(allocator: std.mem.Allocator, path: []const u8, bytes: []const u8) !void {
    const parent = std.fs.path.dirname(path) orelse return error.InvalidJournalPath;
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    try std.Io.Dir.createDirPath(std.Io.Dir.cwd(), io_backend.io(), parent);
    try zts.file_io.writeFile(allocator, path, bytes);
    try syncFile(allocator, path);
    try syncDirectory(allocator, parent);
}

fn durableWriteWithDigest(allocator: std.mem.Allocator, path: []const u8, bytes: []const u8) !void {
    try durableWrite(allocator, path, bytes);
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
    const digest_hex = std.fmt.bytesToHex(digest, .lower);
    const digest_path = try std.fmt.allocPrint(allocator, "{s}.sha256", .{path});
    defer allocator.free(digest_path);
    try durableWrite(allocator, digest_path, &digest_hex);
}

fn readVerifiedFile(
    allocator: std.mem.Allocator,
    path: []const u8,
    max_bytes: usize,
) ![]u8 {
    const bytes = try zts.file_io.readFile(allocator, path, max_bytes);
    errdefer allocator.free(bytes);
    const digest_path = try std.fmt.allocPrint(allocator, "{s}.sha256", .{path});
    defer allocator.free(digest_path);
    const digest_bytes = try zts.file_io.readFile(allocator, digest_path, 64);
    defer allocator.free(digest_bytes);
    const expected = parseDigest(digest_bytes) orelse return error.CorruptTransactionJournal;
    var actual: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &actual, .{});
    if (!std.mem.eql(u8, &actual, &expected)) return error.CorruptTransactionJournal;
    return bytes;
}

fn syncFile(allocator: std.mem.Allocator, path: []const u8) !void {
    const path_z = try allocator.dupeZ(u8, path);
    defer allocator.free(path_z);
    const fd = try std.posix.openatZ(std.posix.AT.FDCWD, path_z, .{ .ACCMODE = .RDONLY }, 0);
    defer std.Io.Threaded.closeFd(fd);
    if (std.c.fsync(fd) != 0) return error.SyncFailure;
}

// `iterate` is what keeps the descriptor off `O_PATH`. Linux opens a
// directory with `O_PATH` unless iteration is requested, and `fsync` on an
// `O_PATH` descriptor fails with EBADF; macOS has no `O_PATH`, so the same code
// syncs there and refuses every transaction on Linux.
fn syncDirectory(allocator: std.mem.Allocator, path: []const u8) !void {
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    var dir = try std.Io.Dir.openDirAbsolute(io_backend.io(), path, .{ .iterate = true });
    defer dir.close(io_backend.io());
    if (std.c.fsync(dir.handle) != 0) return error.DirectorySyncFailure;
}

fn renameAndSync(allocator: std.mem.Allocator, source: []const u8, target: []const u8) !void {
    const source_z = try allocator.dupeZ(u8, source);
    defer allocator.free(source_z);
    const target_z = try allocator.dupeZ(u8, target);
    defer allocator.free(target_z);
    if (std.c.rename(source_z, target_z) != 0) return error.RenameFailure;
    try syncDirectory(allocator, std.fs.path.dirname(target) orelse return error.InvalidTargetPath);
}

fn writeMarker(allocator: std.mem.Allocator, transaction_dir: []const u8, name: []const u8) !void {
    const path = try markerPath(allocator, transaction_dir, name);
    defer allocator.free(path);
    try durableWrite(allocator, path, name);
}

fn markerPresent(allocator: std.mem.Allocator, transaction_dir: []const u8, name: []const u8) !bool {
    const path = try markerPath(allocator, transaction_dir, name);
    defer allocator.free(path);
    const bytes = zts.file_io.readFile(allocator, path, 128) catch |err| switch (err) {
        error.FileNotFound => return false,
        else => return err,
    };
    defer allocator.free(bytes);
    if (!std.mem.eql(u8, bytes, name)) return error.CorruptTransactionJournal;
    return true;
}

fn writeProgressMarker(allocator: std.mem.Allocator, transaction_dir: []const u8, index: usize) !void {
    const name = try std.fmt.allocPrint(allocator, "applied-{d}", .{index});
    defer allocator.free(name);
    try writeMarker(allocator, transaction_dir, name);
}

fn markerPath(allocator: std.mem.Allocator, transaction_dir: []const u8, name: []const u8) ![]u8 {
    return std.fs.path.resolve(allocator, &.{ transaction_dir, name });
}

fn imagePath(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    index: usize,
    suffix: []const u8,
) ![]u8 {
    const filename = try std.fmt.allocPrint(allocator, "{d}.{s}", .{ index, suffix });
    defer allocator.free(filename);
    return std.fs.path.resolve(allocator, &.{ transaction_dir, "images", filename });
}

fn transactionPath(allocator: std.mem.Allocator, workspace_root: []const u8, proof_id: *const [64]u8) ![]u8 {
    const canonical_workspace = try common.resolveInsideWorkspace(allocator, workspace_root, ".");
    defer allocator.free(canonical_workspace);
    return std.fs.path.resolve(allocator, &.{ canonical_workspace, ".zttp", "change-sets", proof_id[0..] });
}

fn loadManifest(allocator: std.mem.Allocator, transaction_dir: []const u8) !std.json.Parsed(Manifest) {
    const path = try std.fs.path.resolve(allocator, &.{ transaction_dir, "manifest.json" });
    defer allocator.free(path);
    const bytes = try readVerifiedFile(allocator, path, 4 * 1024 * 1024);
    defer allocator.free(bytes);
    const parsed = try std.json.parseFromSlice(Manifest, allocator, bytes, .{
        .allocate = .alloc_always,
        .duplicate_field_behavior = .@"error",
        .ignore_unknown_fields = false,
    });
    if (parsed.value.schema_version != journal_schema_version or
        !isCanonicalProofId(parsed.value.proof_id) or
        parsed.value.changes.len == 0 or
        parsed.value.changes.len > change_set.max_changes)
    {
        var owned = parsed;
        owned.deinit();
        return error.CorruptTransactionJournal;
    }
    return parsed;
}

fn validateManifestAndImages(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    manifest: Manifest,
) !void {
    if (!std.fs.path.isAbsolute(manifest.workspace_root)) return error.CorruptTransactionJournal;
    const change_sets_dir = std.fs.path.dirname(transaction_dir) orelse return error.CorruptTransactionJournal;
    const state_dir = std.fs.path.dirname(change_sets_dir) orelse return error.CorruptTransactionJournal;
    const expected_workspace = std.fs.path.dirname(state_dir) orelse return error.CorruptTransactionJournal;
    if (!std.mem.eql(u8, manifest.workspace_root, expected_workspace) or
        !std.mem.eql(u8, manifest.proof_id, std.fs.path.basename(transaction_dir)))
    {
        return error.CorruptTransactionJournal;
    }

    for (manifest.changes, 0..) |change, index| {
        if (!std.fs.path.isAbsolute(change.path) or !common.isPathInsideRoot(manifest.workspace_root, change.path)) {
            return error.CorruptTransactionJournal;
        }
        for (manifest.changes[0..index]) |prior| {
            if (std.mem.eql(u8, prior.path, change.path)) return error.CorruptTransactionJournal;
        }
        const baseline_digest = parseDigest(change.baseline_sha256) orelse return error.CorruptTransactionJournal;
        const candidate_digest = parseDigest(change.candidate_sha256) orelse return error.CorruptTransactionJournal;
        const after_path = try imagePath(allocator, transaction_dir, index, "after");
        defer allocator.free(after_path);
        const after = try zts.file_io.readFile(allocator, after_path, change_set.max_file_bytes);
        defer allocator.free(after);
        const after_digest = change_set.digestBaseline(after);
        if (!std.mem.eql(u8, &after_digest, &candidate_digest)) return error.CorruptTransactionJournal;

        const before_path = try imagePath(allocator, transaction_dir, index, "before");
        defer allocator.free(before_path);
        if (std.mem.eql(u8, change.baseline_state, "present")) {
            const before = try zts.file_io.readFile(allocator, before_path, change_set.max_file_bytes);
            defer allocator.free(before);
            const before_digest = change_set.digestBaseline(before);
            if (!std.mem.eql(u8, &before_digest, &baseline_digest)) return error.CorruptTransactionJournal;
        } else if (std.mem.eql(u8, change.baseline_state, "absent")) {
            if (try pathExists(allocator, before_path) or
                !std.mem.eql(u8, &baseline_digest, &change_set.digestBaseline(null)))
            {
                return error.CorruptTransactionJournal;
            }
        } else {
            return error.CorruptTransactionJournal;
        }
    }
}

fn validateReceipt(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    proof_id: []const u8,
) !void {
    const path = try std.fs.path.resolve(allocator, &.{ transaction_dir, "receipt.json" });
    defer allocator.free(path);
    const bytes = try readVerifiedFile(allocator, path, 64 * 1024 * 1024);
    defer allocator.free(bytes);
    var parsed = std.json.parseFromSlice(std.json.Value, allocator, bytes, .{}) catch
        return error.CorruptTransactionJournal;
    defer parsed.deinit();
    if (parsed.value != .object) return error.CorruptTransactionJournal;
    const object = parsed.value.object;
    const kind = object.get("kind") orelse return error.CorruptTransactionJournal;
    const transaction_id = object.get("transaction_id") orelse return error.CorruptTransactionJournal;
    if (kind != .string or transaction_id != .string or
        !std.mem.eql(u8, kind.string, "verified_change_set") or
        !std.mem.eql(u8, transaction_id.string, proof_id))
    {
        return error.CorruptTransactionJournal;
    }
}

fn deleteFileIfPresent(allocator: std.mem.Allocator, path: []const u8) !void {
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    std.Io.Dir.cwd().deleteFile(io_backend.io(), path) catch |err| switch (err) {
        error.FileNotFound => return,
        else => return err,
    };
}

fn deleteTransactionDirectory(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    options: RecoveryOptions,
) !void {
    const parent_path = std.fs.path.dirname(transaction_dir) orelse return error.CorruptTransactionDirectory;
    const name = std.fs.path.basename(transaction_dir);
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    // `iterate` keeps the descriptor off `O_PATH` so the fsync below works on
    // Linux; see `syncDirectory`.
    var parent = try std.Io.Dir.openDirAbsolute(io_backend.io(), parent_path, .{ .iterate = true });
    defer parent.close(io_backend.io());
    try parent.deleteTree(io_backend.io(), name);
    if (options.fault == .before_transaction_directory_sync) return error.DirectorySyncFailure;
    if (std.c.fsync(parent.handle) != 0) return error.DirectorySyncFailure;
}

fn readStateDigest(allocator: std.mem.Allocator, path: []const u8) ![32]u8 {
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    const stat = std.Io.Dir.cwd().statFile(io_backend.io(), path, .{ .follow_symlinks = false }) catch |err| switch (err) {
        error.FileNotFound, error.NotDir => return change_set.digestBaseline(null),
        else => return err,
    };
    if (stat.kind != .file) return error.NonRegularTransactionTarget;
    const bytes = zts.file_io.readFile(allocator, path, change_set.max_file_bytes) catch |err| switch (err) {
        error.FileNotFound => return change_set.digestBaseline(null),
        else => return err,
    };
    defer allocator.free(bytes);
    return change_set.digestBaseline(bytes);
}

fn parseDigest(value: []const u8) ?[32]u8 {
    if (value.len != 64) return null;
    var out: [32]u8 = undefined;
    _ = std.fmt.hexToBytes(&out, value) catch return null;
    return out;
}

fn pathExists(allocator: std.mem.Allocator, path: []const u8) !bool {
    var io_backend = std.Io.Threaded.init(allocator, .{ .environ = .empty });
    defer io_backend.deinit();
    _ = std.Io.Dir.cwd().statFile(io_backend.io(), path, .{ .follow_symlinks = false }) catch |err| switch (err) {
        error.FileNotFound, error.NotDir => return false,
        else => return err,
    };
    return true;
}

fn isCanonicalProofId(value: []const u8) bool {
    if (value.len != 64) return false;
    for (value) |byte| if (!std.ascii.isDigit(byte) and !(byte >= 'a' and byte <= 'f')) return false;
    return true;
}

fn lockExclusiveNonBlocking(fd: std.c.fd_t) !void {
    while (true) switch (std.posix.errno(std.c.flock(fd, std.posix.LOCK.EX | std.posix.LOCK.NB))) {
        .SUCCESS => return,
        .INTR => continue,
        .AGAIN => return error.WorkspaceChangeSetActive,
        else => return error.WorkspaceLockFailed,
    };
}

const testing = std.testing;

test "recovery planner publishes exact target actions" {
    const baseline: [32]u8 = @splat(0x11);
    const candidate: [32]u8 = @splat(0x22);
    const changes = [_]ManifestChange{
        .{ .path = "a", .baseline_state = "present", .baseline_sha256 = "", .candidate_sha256 = "" },
        .{ .path = "b", .baseline_state = "present", .baseline_sha256 = "", .candidate_sha256 = "" },
    };
    const manifest: Manifest = .{
        .schema_version = journal_schema_version,
        .proof_id = "",
        .workspace_root = "",
        .changes = &changes,
    };
    const Case = struct {
        baseline: [32]u8,
        candidate: [32]u8,
        current: [2][32]u8,
        expected: [2]TargetAction,
    };
    const cases = [_]Case{
        .{ .baseline = baseline, .candidate = candidate, .current = .{ baseline, baseline }, .expected = .{ .write_candidate, .write_candidate } },
        .{ .baseline = baseline, .candidate = candidate, .current = .{ baseline, candidate }, .expected = .{ .write_candidate, .keep_candidate } },
        .{ .baseline = baseline, .candidate = candidate, .current = .{ candidate, baseline }, .expected = .{ .keep_candidate, .write_candidate } },
        .{ .baseline = baseline, .candidate = candidate, .current = .{ candidate, candidate }, .expected = .{ .keep_candidate, .keep_candidate } },
        .{ .baseline = baseline, .candidate = baseline, .current = .{ baseline, baseline }, .expected = .{ .keep_candidate, .keep_candidate } },
    };
    for (cases) |case| {
        const actions = try testing.allocator.alloc(TargetAction, changes.len);
        var planner: RecoveryPlanner = .{ .applying = .{
            .manifest = manifest,
            .actions = actions,
            .next_index = 0,
        } };
        var planner_owned = true;
        defer if (planner_owned) planner.deinit(testing.allocator);
        for (case.current) |current| try planner.observe(.{
            .current = current,
            .baseline = case.baseline,
            .candidate = case.candidate,
        });
        var plan = try planner.finish();
        planner_owned = false;
        defer plan.deinit(testing.allocator);
        switch (plan) {
            .applying => |applying| try testing.expectEqualSlices(
                TargetAction,
                &case.expected,
                applying.actions,
            ),
            .unprepared, .aborted, .committed, .prepared => return error.TestUnexpectedResult,
        }
    }
}

test "recovery planner refuses incomplete publication" {
    const baseline: [32]u8 = @splat(0x11);
    const candidate: [32]u8 = @splat(0x22);
    const changes = [_]ManifestChange{
        .{ .path = "a", .baseline_state = "present", .baseline_sha256 = "", .candidate_sha256 = "" },
        .{ .path = "b", .baseline_state = "present", .baseline_sha256 = "", .candidate_sha256 = "" },
    };
    const actions = try testing.allocator.alloc(TargetAction, changes.len);
    var planner: RecoveryPlanner = .{ .applying = .{
        .manifest = .{
            .schema_version = journal_schema_version,
            .proof_id = "",
            .workspace_root = "",
            .changes = &changes,
        },
        .actions = actions,
        .next_index = 0,
    } };
    var planner_owned = true;
    defer if (planner_owned) planner.deinit(testing.allocator);
    try planner.observe(.{
        .current = baseline,
        .baseline = baseline,
        .candidate = candidate,
    });
    if (planner.finish()) |finished| {
        planner_owned = false;
        var plan = finished;
        defer plan.deinit(testing.allocator);
        return error.TestExpectedError;
    } else |err| {
        try testing.expectEqual(error.IncompleteRecoveryPlan, err);
    }
}

test "recovery planner conflict publishes no plan" {
    const baseline: [32]u8 = @splat(0x11);
    const candidate: [32]u8 = @splat(0x22);
    const third: [32]u8 = @splat(0x33);
    const changes = [_]ManifestChange{
        .{ .path = "a", .baseline_state = "present", .baseline_sha256 = "", .candidate_sha256 = "" },
    };
    const actions = try testing.allocator.alloc(TargetAction, changes.len);
    var planner: RecoveryPlanner = .{ .applying = .{
        .manifest = .{
            .schema_version = journal_schema_version,
            .proof_id = "",
            .workspace_root = "",
            .changes = &changes,
        },
        .actions = actions,
        .next_index = 0,
    } };
    var planner_owned = true;
    defer if (planner_owned) planner.deinit(testing.allocator);
    try testing.expectError(error.WorkspaceRecoveryConflict, planner.observe(.{
        .current = third,
        .baseline = baseline,
        .candidate = candidate,
    }));
    if (planner.finish()) |finished| {
        planner_owned = false;
        var plan = finished;
        defer plan.deinit(testing.allocator);
        return error.TestExpectedError;
    } else |err| {
        try testing.expectEqual(error.IncompleteRecoveryPlan, err);
    }
}

const Fixture = struct {
    root: []u8,
    prepared: change_set.PreparedChangeSet,
    snapshot: workspace_snapshot.Snapshot,
    proof: aggregate_proof.AggregateProof,

    fn init(allocator: std.mem.Allocator, tmp: *std.testing.TmpDir) !Fixture {
        try tmp.dir.createDirPath(testing.io, "src");
        try tmp.dir.writeFile(testing.io, .{ .sub_path = "src/a.ts", .data = "old-a" });
        try tmp.dir.writeFile(testing.io, .{ .sub_path = "src/b.ts", .data = "old-b" });
        try tmp.dir.writeFile(testing.io, .{ .sub_path = "src/context.ts", .data = "stable" });
        const root_z = try std.Io.Dir.realPathFileAlloc(tmp.dir, testing.io, ".", allocator);
        defer allocator.free(root_z);
        const root = try allocator.dupe(u8, root_z);
        errdefer allocator.free(root);
        const tail = [_]@import("turn.zig").Change{.{ .file = "src/b.ts", .content = "new-b" }};
        var prepared = try change_set.prepare(allocator, root, .{
            .file = "src/a.ts",
            .content = "new-a",
            .additional = &tail,
        });
        errdefer prepared.deinit(allocator);
        var snapshot = try workspace_snapshot.Snapshot.capture(allocator, &prepared);
        errdefer snapshot.deinit(allocator);
        const roots = try allocator.alloc([]u8, 1);
        roots[0] = try allocator.dupe(u8, "src/a.ts");
        return .{
            .root = root,
            .prepared = prepared,
            .snapshot = snapshot,
            .proof = .{
                .proof_id = @splat('a'),
                .policy_hash = zts.policyHash(),
                .read_set_digest = @splat('b'),
                .proof_roots = roots,
                .diagnostics = try allocator.alloc(aggregate_proof.Diagnostic, 0),
                .system_proven = false,
            },
        };
    }

    fn initMixed(allocator: std.mem.Allocator, tmp: *std.testing.TmpDir) !Fixture {
        try tmp.dir.createDirPath(testing.io, "src");
        try tmp.dir.writeFile(testing.io, .{ .sub_path = "src/a.ts", .data = "old-a" });
        try tmp.dir.writeFile(testing.io, .{ .sub_path = "src/context.ts", .data = "stable" });
        const root_z = try std.Io.Dir.realPathFileAlloc(tmp.dir, testing.io, ".", allocator);
        defer allocator.free(root_z);
        const root = try allocator.dupe(u8, root_z);
        errdefer allocator.free(root);
        const tail = [_]@import("turn.zig").Change{.{ .file = "src/new.ts", .content = "new-file" }};
        var prepared = try change_set.prepare(allocator, root, .{
            .file = "src/a.ts",
            .content = "new-a",
            .additional = &tail,
        });
        errdefer prepared.deinit(allocator);
        var snapshot = try workspace_snapshot.Snapshot.capture(allocator, &prepared);
        errdefer snapshot.deinit(allocator);
        const roots = try allocator.alloc([]u8, 1);
        roots[0] = try allocator.dupe(u8, "src/a.ts");
        return .{
            .root = root,
            .prepared = prepared,
            .snapshot = snapshot,
            .proof = .{
                .proof_id = @splat('c'),
                .policy_hash = zts.policyHash(),
                .read_set_digest = @splat('d'),
                .proof_roots = roots,
                .diagnostics = try allocator.alloc(aggregate_proof.Diagnostic, 0),
                .system_proven = false,
            },
        };
    }

    fn deinit(self: *Fixture, allocator: std.mem.Allocator) void {
        self.proof.deinit(allocator);
        self.snapshot.deinit(allocator);
        self.prepared.deinit(allocator);
        allocator.free(self.root);
    }
};

const MarkerCaseOutcome = enum {
    corrupt,
    delete_transaction,
    preserve_committed,
    roll_forward,
};

const marker_prepared: u8 = 1 << 0;
const marker_applying: u8 = 1 << 1;
const marker_committed: u8 = 1 << 2;
const marker_receipted: u8 = 1 << 3;
const marker_aborted: u8 = 1 << 4;

fn markerSet(mask: u8, marker: u8) bool {
    return mask & marker != 0;
}

const marker_case_outcomes = [32]MarkerCaseOutcome{
    // 0b0_0000 through 0b0_0111.
    .delete_transaction,
    .delete_transaction,
    .corrupt,
    .roll_forward,
    .corrupt,
    .preserve_committed,
    .corrupt,
    .preserve_committed,
    // 0b0_1000 through 0b0_1111.
    .corrupt,
    .delete_transaction,
    .corrupt,
    .roll_forward,
    .corrupt,
    .preserve_committed,
    .corrupt,
    .preserve_committed,
    // 0b1_0000 through 0b1_0111. Aborted wins whenever prepared is present.
    .delete_transaction,
    .delete_transaction,
    .corrupt,
    .delete_transaction,
    .corrupt,
    .delete_transaction,
    .corrupt,
    .delete_transaction,
    // 0b1_1000 through 0b1_1111. Receipted does not change aborted precedence.
    .corrupt,
    .delete_transaction,
    .corrupt,
    .delete_transaction,
    .corrupt,
    .delete_transaction,
    .corrupt,
    .delete_transaction,
};

fn setMarker(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    name: []const u8,
    present: bool,
) !void {
    const path = try markerPath(allocator, transaction_dir, name);
    defer allocator.free(path);
    if (present) {
        try writeMarker(allocator, transaction_dir, name);
    } else {
        try deleteFileIfPresent(allocator, path);
    }
}

fn writeMalformedMarker(
    allocator: std.mem.Allocator,
    transaction_dir: []const u8,
    name: []const u8,
) !void {
    const path = try markerPath(allocator, transaction_dir, name);
    defer allocator.free(path);
    try zts.file_io.writeFile(allocator, path, "truncated");
}

fn expectFixtureCandidates(fixture: *const Fixture, candidates: bool) !void {
    for (fixture.prepared.changes) |change| {
        const bytes = try zts.file_io.readFile(testing.allocator, change.resolved_path, 64);
        defer testing.allocator.free(bytes);
        try testing.expectEqualStrings(
            if (candidates) change.candidate else change.baseline.bytes().?,
            bytes,
        );
    }
}

fn expectPendingReceiptCount(lock: *const WorkspaceLock, root: []const u8, expected: usize) !void {
    const pending = try pendingReceiptsLocked(testing.allocator, lock, root);
    defer {
        for (pending) |*receipt| receipt.deinit(testing.allocator);
        testing.allocator.free(pending);
    }
    try testing.expectEqual(expected, pending.len);
}

fn assertMarkerCase(mask: u8) !void {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_prepared,
        }),
    );
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    try setMarker(testing.allocator, transaction_dir, "prepared", markerSet(mask, marker_prepared));
    try setMarker(testing.allocator, transaction_dir, "applying", markerSet(mask, marker_applying));
    try setMarker(testing.allocator, transaction_dir, "committed", markerSet(mask, marker_committed));
    try setMarker(testing.allocator, transaction_dir, "receipted", markerSet(mask, marker_receipted));
    try setMarker(testing.allocator, transaction_dir, "aborted", markerSet(mask, marker_aborted));

    switch (marker_case_outcomes[mask]) {
        .corrupt => {
            try testing.expectError(
                error.CorruptTransactionJournal,
                recoverAllLocked(testing.allocator, &lock, fixture.root),
            );
            try testing.expect(try pathExists(testing.allocator, transaction_dir));
            try expectFixtureCandidates(&fixture, false);
        },
        .delete_transaction => {
            try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
            try testing.expect(!try pathExists(testing.allocator, transaction_dir));
            try expectFixtureCandidates(&fixture, false);
            try expectPendingReceiptCount(&lock, fixture.root, 0);
        },
        .preserve_committed => {
            try testing.expectEqual(@as(usize, 0), try recoverAllLocked(testing.allocator, &lock, fixture.root));
            try testing.expect(try pathExists(testing.allocator, transaction_dir));
            try expectFixtureCandidates(&fixture, false);
            try expectPendingReceiptCount(
                &lock,
                fixture.root,
                if (markerSet(mask, marker_receipted)) 0 else 1,
            );
        },
        .roll_forward => {
            try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
            try testing.expect(try pathExists(testing.allocator, transaction_dir));
            try expectFixtureCandidates(&fixture, true);
            try expectPendingReceiptCount(
                &lock,
                fixture.root,
                if (markerSet(mask, marker_receipted)) 0 else 1,
            );
        },
    }
}

const TargetState = enum { baseline, candidate, third };

fn setTargetState(change: change_set.PreparedChange, state: TargetState) !void {
    switch (state) {
        .baseline => if (change.baseline.bytes()) |bytes|
            try durableWrite(testing.allocator, change.resolved_path, bytes)
        else
            try deleteFileIfPresent(testing.allocator, change.resolved_path),
        .candidate => try durableWrite(testing.allocator, change.resolved_path, change.candidate),
        .third => try durableWrite(testing.allocator, change.resolved_path, "third-state"),
    }
}

fn expectTargetState(change: change_set.PreparedChange, state: TargetState) !void {
    const expected: ?[]const u8 = switch (state) {
        .baseline => change.baseline.bytes(),
        .candidate => change.candidate,
        .third => "third-state",
    };
    if (expected) |bytes| {
        const current = try zts.file_io.readFile(testing.allocator, change.resolved_path, 64);
        defer testing.allocator.free(current);
        try testing.expectEqualStrings(bytes, current);
    } else {
        try testing.expect(!try pathExists(testing.allocator, change.resolved_path));
    }
}

fn assertTargetMatrixCase(mixed: bool, first: TargetState, second: TargetState) !void {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = if (mixed)
        try Fixture.initMixed(testing.allocator, &tmp)
    else
        try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_applying,
        }),
    );
    try setTargetState(fixture.prepared.changes[0], first);
    try setTargetState(fixture.prepared.changes[1], second);

    if (first == .third or second == .third) {
        try testing.expectError(
            error.WorkspaceRecoveryConflict,
            recoverAllLocked(testing.allocator, &lock, fixture.root),
        );
        try expectTargetState(fixture.prepared.changes[0], first);
        try expectTargetState(fixture.prepared.changes[1], second);
    } else {
        try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
        try expectTargetState(fixture.prepared.changes[0], .candidate);
        try expectTargetState(fixture.prepared.changes[1], .candidate);
    }
}

test "recovery preserves marker precedence for combinations 0 through 7" {
    var mask: u8 = 0;
    while (mask < 8) : (mask += 1) try assertMarkerCase(mask);
}

test "recovery preserves marker precedence for combinations 8 through 15" {
    var mask: u8 = 8;
    while (mask < 16) : (mask += 1) try assertMarkerCase(mask);
}

test "recovery preserves marker precedence for combinations 16 through 23" {
    var mask: u8 = 16;
    while (mask < 24) : (mask += 1) try assertMarkerCase(mask);
}

test "recovery preserves marker precedence for combinations 24 through 31" {
    var mask: u8 = 24;
    while (mask < 32) : (mask += 1) try assertMarkerCase(mask);
}

test "recovery ignores progress markers when classifying a transaction" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_prepared,
        }),
    );
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    try writeProgressMarker(testing.allocator, transaction_dir, 0);
    try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
    try testing.expect(!try pathExists(testing.allocator, transaction_dir));
    try expectFixtureCandidates(&fixture, false);
}

test "recovery validates images before an aborted marker takes precedence" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_prepared,
        }),
    );
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    const after_path = try imagePath(testing.allocator, transaction_dir, 0, "after");
    defer testing.allocator.free(after_path);
    try zts.file_io.writeFile(testing.allocator, after_path, "corrupt");
    try writeMarker(testing.allocator, transaction_dir, "aborted");
    try testing.expectError(
        error.CorruptTransactionJournal,
        recoverAllLocked(testing.allocator, &lock, fixture.root),
    );
    try testing.expect(try pathExists(testing.allocator, transaction_dir));
    try expectFixtureCandidates(&fixture, false);
}

test "recovery rejects truncated prepared and applying markers before source writes" {
    const names = [_][]const u8{ "prepared", "applying" };
    for (names) |name| {
        var tmp = testing.tmpDir(.{});
        defer tmp.cleanup();
        var fixture = try Fixture.init(testing.allocator, &tmp);
        defer fixture.deinit(testing.allocator);
        var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
        defer lock.deinit();
        try testing.expectError(
            error.InjectedTransactionFailure,
            commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
                .fault = .after_prepared,
            }),
        );
        const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
        defer testing.allocator.free(transaction_dir);
        try writeMalformedMarker(testing.allocator, transaction_dir, name);
        try testing.expectError(
            error.CorruptTransactionJournal,
            recoverAllLocked(testing.allocator, &lock, fixture.root),
        );
        try expectFixtureCandidates(&fixture, false);
    }
}

test "recovery does not read markers below the selected precedence" {
    const Selected = enum { aborted, committed, prepared, applying };
    const cases = [_]Selected{ .aborted, .committed, .prepared, .applying };
    for (cases) |selected| {
        var tmp = testing.tmpDir(.{});
        defer tmp.cleanup();
        var fixture = try Fixture.init(testing.allocator, &tmp);
        defer fixture.deinit(testing.allocator);
        var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
        defer lock.deinit();
        try testing.expectError(
            error.InjectedTransactionFailure,
            commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
                .fault = .after_prepared,
            }),
        );
        const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
        defer testing.allocator.free(transaction_dir);
        switch (selected) {
            .aborted => {
                try writeMarker(testing.allocator, transaction_dir, "aborted");
                try writeMalformedMarker(testing.allocator, transaction_dir, "committed");
                try writeMalformedMarker(testing.allocator, transaction_dir, "applying");
                try writeMalformedMarker(testing.allocator, transaction_dir, "receipted");
            },
            .committed => {
                try writeMarker(testing.allocator, transaction_dir, "committed");
                try writeMalformedMarker(testing.allocator, transaction_dir, "applying");
                try writeMalformedMarker(testing.allocator, transaction_dir, "receipted");
            },
            .prepared => try writeMalformedMarker(testing.allocator, transaction_dir, "receipted"),
            .applying => {
                try writeMarker(testing.allocator, transaction_dir, "applying");
                try writeMalformedMarker(testing.allocator, transaction_dir, "receipted");
            },
        }
        const recovered = try recoverAllLocked(testing.allocator, &lock, fixture.root);
        try testing.expectEqual(
            @as(usize, if (selected == .committed) 0 else 1),
            recovered,
        );
        try expectFixtureCandidates(&fixture, selected == .applying);
        try testing.expectEqual(
            selected == .committed or selected == .applying,
            try pathExists(testing.allocator, transaction_dir),
        );
    }
}

test "aborted recovery ignores a corrupt receipt but committed recovery validates it" {
    const Cases = struct {
        fn run(committed: bool) !void {
            var tmp = testing.tmpDir(.{});
            defer tmp.cleanup();
            var fixture = try Fixture.init(testing.allocator, &tmp);
            defer fixture.deinit(testing.allocator);
            var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
            defer lock.deinit();
            try testing.expectError(
                error.InjectedTransactionFailure,
                commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
                    .fault = .after_prepared,
                }),
            );
            const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
            defer testing.allocator.free(transaction_dir);
            const receipt_path = try std.fs.path.resolve(testing.allocator, &.{ transaction_dir, "receipt.json" });
            defer testing.allocator.free(receipt_path);
            try zts.file_io.writeFile(testing.allocator, receipt_path, "corrupt");
            try writeMarker(
                testing.allocator,
                transaction_dir,
                if (committed) "committed" else "aborted",
            );
            if (committed) {
                try testing.expectError(
                    error.CorruptTransactionJournal,
                    recoverAllLocked(testing.allocator, &lock, fixture.root),
                );
                try testing.expect(try pathExists(testing.allocator, transaction_dir));
            } else {
                try testing.expectEqual(
                    @as(usize, 1),
                    try recoverAllLocked(testing.allocator, &lock, fixture.root),
                );
                try testing.expect(!try pathExists(testing.allocator, transaction_dir));
            }
            try expectFixtureCandidates(&fixture, false);
        }
    };
    try Cases.run(false);
    try Cases.run(true);
}

test "recovery plans every present target state before source writes" {
    const states = [_]TargetState{ .baseline, .candidate, .third };
    for (states) |first| for (states) |second| try assertTargetMatrixCase(false, first, second);
}

test "recovery plans mixed existing and new target states before source writes" {
    const states = [_]TargetState{ .baseline, .candidate, .third };
    for (states) |first| for (states) |second| try assertTargetMatrixCase(true, first, second);
}

test "recovery preserves target conflict and read error precedence" {
    const Case = enum { conflict_first, nonregular_first };
    const cases = [_]Case{ .conflict_first, .nonregular_first };
    for (cases) |case| {
        var tmp = testing.tmpDir(.{});
        defer tmp.cleanup();
        var fixture = try Fixture.init(testing.allocator, &tmp);
        defer fixture.deinit(testing.allocator);
        var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
        defer lock.deinit();
        try testing.expectError(
            error.InjectedTransactionFailure,
            commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
                .fault = .after_applying,
            }),
        );

        const nonregular_index: usize = if (case == .conflict_first) 1 else 0;
        const third_index: usize = 1 - nonregular_index;
        try zts.file_io.writeFile(
            testing.allocator,
            fixture.prepared.changes[third_index].resolved_path,
            "third-state",
        );
        try deleteFileIfPresent(
            testing.allocator,
            fixture.prepared.changes[nonregular_index].resolved_path,
        );
        var io_backend = std.Io.Threaded.init(testing.allocator, .{ .environ = .empty });
        defer io_backend.deinit();
        try std.Io.Dir.createDirPath(
            std.Io.Dir.cwd(),
            io_backend.io(),
            fixture.prepared.changes[nonregular_index].resolved_path,
        );

        if (case == .conflict_first) {
            try testing.expectError(
                error.WorkspaceRecoveryConflict,
                recoverAllLocked(testing.allocator, &lock, fixture.root),
            );
        } else {
            try testing.expectError(
                error.NonRegularTransactionTarget,
                recoverAllLocked(testing.allocator, &lock, fixture.root),
            );
        }
        try expectTargetState(fixture.prepared.changes[third_index], .third);
        const stat = try std.Io.Dir.cwd().statFile(
            io_backend.io(),
            fixture.prepared.changes[nonregular_index].resolved_path,
            .{ .follow_symlinks = false },
        );
        try testing.expectEqual(std.Io.File.Kind.directory, stat.kind);
    }
}

test "transaction commits every path and one durable receipt" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    var receipt = try commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{});
    defer receipt.deinit(testing.allocator);
    try testing.expect(try pathExists(testing.allocator, receipt.receipt_path));
    for (fixture.prepared.changes) |change| {
        const bytes = try zts.file_io.readFile(testing.allocator, change.resolved_path, 64);
        defer testing.allocator.free(bytes);
        try testing.expectEqualStrings(change.candidate, bytes);
    }
    const pending = try pendingReceiptsLocked(testing.allocator, &lock, fixture.root);
    defer {
        for (pending) |*item| item.deinit(testing.allocator);
        testing.allocator.free(pending);
    }
    try testing.expectEqual(@as(usize, 1), pending.len);
    try testing.expectEqualSlices(u8, &fixture.proof.proof_id, &pending[0].transaction_id);
    try markReceiptedLocked(testing.allocator, &lock, fixture.root, &fixture.proof.proof_id);
    const acknowledged = try pendingReceiptsLocked(testing.allocator, &lock, fixture.root);
    defer testing.allocator.free(acknowledged);
    try testing.expectEqual(@as(usize, 0), acknowledged.len);
}

test "recovery rolls a partial rename sequence forward" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .{ .after_rename = 0 },
        }),
    );
    try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
    for (fixture.prepared.changes) |change| {
        const bytes = try zts.file_io.readFile(testing.allocator, change.resolved_path, 64);
        defer testing.allocator.free(bytes);
        try testing.expectEqualStrings(change.candidate, bytes);
    }
    const pending = try pendingReceiptsLocked(testing.allocator, &lock, fixture.root);
    defer {
        for (pending) |*item| item.deinit(testing.allocator);
        testing.allocator.free(pending);
    }
    try testing.expectEqual(@as(usize, 1), pending.len);
}

test "recovery never overwrites a concurrent third state" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .{ .after_rename = 0 },
        }),
    );
    try zts.file_io.writeFile(testing.allocator, fixture.prepared.changes[1].resolved_path, "user-edit");
    try testing.expectError(
        error.WorkspaceRecoveryConflict,
        recoverAllLocked(testing.allocator, &lock, fixture.root),
    );
    const bytes = try zts.file_io.readFile(testing.allocator, fixture.prepared.changes[1].resolved_path, 64);
    defer testing.allocator.free(bytes);
    try testing.expectEqualStrings("user-edit", bytes);
}

test "recovery validates every target before writing any baseline" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_applying,
        }),
    );
    try zts.file_io.writeFile(testing.allocator, fixture.prepared.changes[1].resolved_path, "user-edit");
    try testing.expectError(
        error.WorkspaceRecoveryConflict,
        recoverAllLocked(testing.allocator, &lock, fixture.root),
    );
    const first = try zts.file_io.readFile(testing.allocator, fixture.prepared.changes[0].resolved_path, 64);
    defer testing.allocator.free(first);
    try testing.expectEqualStrings("old-a", first);
}

test "recovery removes a prepared transaction that changed no source" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_prepared,
        }),
    );
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    try testing.expect(try pathExists(testing.allocator, transaction_dir));
    try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
    try testing.expect(!try pathExists(testing.allocator, transaction_dir));
    for (fixture.prepared.changes) |change| {
        const bytes = try zts.file_io.readFile(testing.allocator, change.resolved_path, 64);
        defer testing.allocator.free(bytes);
        try testing.expectEqualStrings(change.baseline.bytes().?, bytes);
    }
}

test "recovery rejects a corrupt candidate image before writing" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_applying,
        }),
    );
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    const after_path = try imagePath(testing.allocator, transaction_dir, 0, "after");
    defer testing.allocator.free(after_path);
    try zts.file_io.writeFile(testing.allocator, after_path, "corrupt");
    try testing.expectError(
        error.CorruptTransactionJournal,
        recoverAllLocked(testing.allocator, &lock, fixture.root),
    );
    for (fixture.prepared.changes) |change| {
        const bytes = try zts.file_io.readFile(testing.allocator, change.resolved_path, 64);
        defer testing.allocator.free(bytes);
        try testing.expectEqualStrings(change.baseline.bytes().?, bytes);
    }
}

test "recovery keeps a committed receipt pending until its durable owner acknowledges it" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_committed,
        }),
    );
    try testing.expectEqual(@as(usize, 0), try recoverAllLocked(testing.allocator, &lock, fixture.root));
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    try testing.expect(!try markerPresent(testing.allocator, transaction_dir, "receipted"));
    const pending = try pendingReceiptsLocked(testing.allocator, &lock, fixture.root);
    defer {
        for (pending) |*item| item.deinit(testing.allocator);
        testing.allocator.free(pending);
    }
    try testing.expectEqual(@as(usize, 1), pending.len);
    try markReceiptedLocked(testing.allocator, &lock, fixture.root, &fixture.proof.proof_id);
    try testing.expect(try markerPresent(testing.allocator, transaction_dir, "receipted"));
}

test "transaction recovery covers journal image receipt stage and rename failures" {
    const FailureCase = struct {
        fault: FaultPoint,
        expected_error: anyerror,
        rolls_forward: bool,
    };
    const cases = [_]FailureCase{
        .{ .fault = .before_manifest_write, .expected_error = error.InjectedTransactionFailure, .rolls_forward = false },
        .{ .fault = .{ .before_image_write = 0 }, .expected_error = error.InjectedTransactionFailure, .rolls_forward = false },
        .{ .fault = .{ .before_image_write = 1 }, .expected_error = error.InjectedTransactionFailure, .rolls_forward = false },
        .{ .fault = .before_receipt_write, .expected_error = error.InjectedTransactionFailure, .rolls_forward = false },
        .{ .fault = .{ .before_stage_write = 0 }, .expected_error = error.InjectedTransactionFailure, .rolls_forward = false },
        .{ .fault = .{ .before_stage_write = 1 }, .expected_error = error.InjectedTransactionFailure, .rolls_forward = false },
        .{ .fault = .{ .before_rename = 0 }, .expected_error = error.RenameFailure, .rolls_forward = true },
        .{ .fault = .{ .before_rename = 1 }, .expected_error = error.RenameFailure, .rolls_forward = true },
    };
    for (cases) |case| {
        var tmp = testing.tmpDir(.{});
        defer tmp.cleanup();
        var fixture = try Fixture.init(testing.allocator, &tmp);
        defer fixture.deinit(testing.allocator);
        var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
        defer lock.deinit();
        try testing.expectError(
            case.expected_error,
            commitLocked(
                testing.allocator,
                &lock,
                &fixture.prepared,
                &fixture.snapshot,
                &fixture.proof,
                .{ .fault = case.fault },
            ),
        );
        try testing.expectEqual(
            @as(usize, 1),
            try recoverAllLocked(testing.allocator, &lock, fixture.root),
        );
        try expectFixtureCandidates(&fixture, case.rolls_forward);
        const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
        defer testing.allocator.free(transaction_dir);
        try testing.expectEqual(
            case.rolls_forward,
            try pathExists(testing.allocator, transaction_dir),
        );
    }
}

test "recovery retries after the durable aborted marker completes" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_prepared,
        }),
    );
    try testing.expectError(
        error.InjectedTransactionFailure,
        recoverAllLockedWithOptions(testing.allocator, &lock, fixture.root, .{
            .fault = .after_aborted_marker,
        }),
    );
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    try testing.expect(try markerPresent(testing.allocator, transaction_dir, "aborted"));
    try expectFixtureCandidates(&fixture, false);
    try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
    try testing.expect(!try pathExists(testing.allocator, transaction_dir));
    try expectFixtureCandidates(&fixture, false);
}

test "recovery reports directory sync failure after namespace deletion" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_prepared,
        }),
    );
    try testing.expectError(
        error.DirectorySyncFailure,
        recoverAllLockedWithOptions(testing.allocator, &lock, fixture.root, .{
            .fault = .before_transaction_directory_sync,
        }),
    );
    // The process sees the deletion, but the injected error means this test
    // makes no claim that the parent directory reached durable storage.
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    try testing.expect(!try pathExists(testing.allocator, transaction_dir));
    try expectFixtureCandidates(&fixture, false);
    try testing.expectEqual(@as(usize, 0), try recoverAllLocked(testing.allocator, &lock, fixture.root));
}

test "recovery accepts exact candidate bytes after write and synchronization errors" {
    const FaultCase = struct {
        fault: RecoveryFaultPoint,
        expected_error: anyerror,
        index: usize,
    };
    const faults = [_]FaultCase{
        .{ .fault = .{ .before_source_file_sync = 0 }, .expected_error = error.SyncFailure, .index = 0 },
        .{ .fault = .{ .before_source_file_sync = 1 }, .expected_error = error.SyncFailure, .index = 1 },
        .{ .fault = .{ .before_source_directory_sync = 0 }, .expected_error = error.DirectorySyncFailure, .index = 0 },
        .{ .fault = .{ .before_source_directory_sync = 1 }, .expected_error = error.DirectorySyncFailure, .index = 1 },
        .{ .fault = .{ .after_source_write = 0 }, .expected_error = error.InjectedTransactionFailure, .index = 0 },
        .{ .fault = .{ .after_source_write = 1 }, .expected_error = error.InjectedTransactionFailure, .index = 1 },
    };
    for (faults) |case| {
        var tmp = testing.tmpDir(.{});
        defer tmp.cleanup();
        var fixture = try Fixture.init(testing.allocator, &tmp);
        defer fixture.deinit(testing.allocator);
        var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
        defer lock.deinit();
        try testing.expectError(
            error.InjectedTransactionFailure,
            commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
                .fault = .after_applying,
            }),
        );
        try testing.expectError(
            case.expected_error,
            recoverAllLockedWithOptions(testing.allocator, &lock, fixture.root, .{ .fault = case.fault }),
        );
        // The complete candidate is visible after each injected boundary.
        // A failed write that leaves other bytes is covered by the conflict
        // test below.
        try expectTargetState(fixture.prepared.changes[0], .candidate);
        try expectTargetState(
            fixture.prepared.changes[1],
            if (case.index == 0) .baseline else .candidate,
        );
        try testing.expectEqual(@as(usize, 1), try recoverAllLocked(testing.allocator, &lock, fixture.root));
        try expectFixtureCandidates(&fixture, true);
    }
}

test "recovery retries after candidate verification and committed marker effects" {
    const FaultCase = enum { after_verification, after_committed };
    const cases = [_]FaultCase{ .after_verification, .after_committed };
    for (cases) |case| {
        var tmp = testing.tmpDir(.{});
        defer tmp.cleanup();
        var fixture = try Fixture.init(testing.allocator, &tmp);
        defer fixture.deinit(testing.allocator);
        var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
        defer lock.deinit();
        try testing.expectError(
            error.InjectedTransactionFailure,
            commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
                .fault = .after_applying,
            }),
        );
        try testing.expectError(
            error.InjectedTransactionFailure,
            recoverAllLockedWithOptions(testing.allocator, &lock, fixture.root, .{
                .fault = switch (case) {
                    .after_verification => .after_candidate_verification,
                    .after_committed => .after_committed_marker,
                },
            }),
        );
        const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
        defer testing.allocator.free(transaction_dir);
        try expectFixtureCandidates(&fixture, true);
        try testing.expectEqual(
            case == .after_committed,
            try markerPresent(testing.allocator, transaction_dir, "committed"),
        );
        const recovered = try recoverAllLocked(testing.allocator, &lock, fixture.root);
        try testing.expectEqual(
            @as(usize, if (case == .after_committed) 0 else 1),
            recovered,
        );
        const pending = try pendingReceiptsLocked(testing.allocator, &lock, fixture.root);
        defer {
            for (pending) |*receipt| receipt.deinit(testing.allocator);
            testing.allocator.free(pending);
        }
        try testing.expectEqual(@as(usize, 1), pending.len);
    }
}

test "a truncated source write conflicts on retry and protects every other target" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.InjectedTransactionFailure,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{
            .fault = .after_applying,
        }),
    );
    try zts.file_io.writeFile(
        testing.allocator,
        fixture.prepared.changes[0].resolved_path,
        "new",
    );
    try testing.expectError(
        error.WorkspaceRecoveryConflict,
        recoverAllLocked(testing.allocator, &lock, fixture.root),
    );
    const truncated = try zts.file_io.readFile(
        testing.allocator,
        fixture.prepared.changes[0].resolved_path,
        64,
    );
    defer testing.allocator.free(truncated);
    try testing.expectEqualStrings("new", truncated);
    try expectTargetState(fixture.prepared.changes[1], .baseline);
}

test "durable acknowledgement failure is idempotent on retry" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    var receipt = try commitLocked(
        testing.allocator,
        &lock,
        &fixture.prepared,
        &fixture.snapshot,
        &fixture.proof,
        .{},
    );
    defer receipt.deinit(testing.allocator);
    try testing.expectError(
        error.InjectedTransactionFailure,
        markReceiptedLockedWithOptions(
            testing.allocator,
            &lock,
            fixture.root,
            &fixture.proof.proof_id,
            .{ .fault = .after_receipted_marker },
        ),
    );
    const transaction_dir = try transactionPath(testing.allocator, fixture.root, &fixture.proof.proof_id);
    defer testing.allocator.free(transaction_dir);
    try testing.expect(try markerPresent(testing.allocator, transaction_dir, "receipted"));
    try markReceiptedLocked(testing.allocator, &lock, fixture.root, &fixture.proof.proof_id);
    const pending = try pendingReceiptsLocked(testing.allocator, &lock, fixture.root);
    defer testing.allocator.free(pending);
    try testing.expectEqual(@as(usize, 0), pending.len);
}

test "full read set mutation causes zero writes" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    var fixture = try Fixture.init(testing.allocator, &tmp);
    defer fixture.deinit(testing.allocator);
    try tmp.dir.writeFile(testing.io, .{ .sub_path = "src/context.ts", .data = "concurrent" });
    var lock = try WorkspaceLock.acquire(testing.allocator, fixture.root);
    defer lock.deinit();
    try testing.expectError(
        error.ProofReadSetChanged,
        commitLocked(testing.allocator, &lock, &fixture.prepared, &fixture.snapshot, &fixture.proof, .{}),
    );
    for (fixture.prepared.changes) |change| {
        const bytes = try zts.file_io.readFile(testing.allocator, change.resolved_path, 64);
        defer testing.allocator.free(bytes);
        try testing.expectEqualStrings(change.baseline.bytes().?, bytes);
    }
}

test "workspace lock excludes a second writer" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    const root_z = try std.Io.Dir.realPathFileAlloc(tmp.dir, testing.io, ".", testing.allocator);
    defer testing.allocator.free(root_z);
    const root = try testing.allocator.dupe(u8, root_z);
    defer testing.allocator.free(root);
    var first = try WorkspaceLock.acquire(testing.allocator, root);
    defer first.deinit();
    try testing.expectError(error.WorkspaceChangeSetActive, WorkspaceLock.acquire(testing.allocator, root));
}
