//! Replay Runner
//!
//! Replays recorded JSONL traces against a handler and reports pass/fail.
//! In diff mode (when a different handler is specified), compares outputs
//! and produces a structured regression report.
//!
//! Usage:
//!   zig build run -- --replay traces.jsonl handler.ts
//!   zig build run -- --replay traces.jsonl handler_v2.ts   (diff mode)

const std = @import("std");
const builtin = @import("builtin");
const zq = @import("zts");
const RuntimeConfig = @import("runtime_config.zig").RuntimeConfig;
const Runtime = @import("zruntime.zig").Runtime;
const HttpRequestView = @import("http_types.zig").HttpRequestView;
const HttpHeader = @import("http_types.zig").HttpHeader;
const HttpResponse = @import("http_types.zig").HttpResponse;
const ExecutionSpec = @import("execution_spec.zig").ExecutionSpec;
const handler_loader = @import("handler_loader.zig");
const runtime_natives = @import("runtime_natives.zig");

const trace = zq.trace;

/// Run the replay engine.
pub fn run(allocator: std.mem.Allocator, spec: ExecutionSpec) !void {
    const replay_path = spec.runtime_config.replay_file_path orelse return error.NoReplayFile;

    var loaded = try loadTraceGroups(allocator, replay_path);
    defer loaded.deinit(allocator);
    const groups = loaded.groups;

    if (groups.len == 0) {
        if (!builtin.is_test) std.log.err("Replay fixture '{s}' contains no request traces", .{replay_path});
        return error.InvalidReplayFixture;
    }

    const handler_source = handler_loader.load(allocator, spec.handler) catch |err| {
        switch (err) {
            error.UnsupportedHandlerSource => std.log.err("Replay requires a file_path or inline_code handler source", .{}),
            else => std.log.err("Replay failed to load handler: {}", .{err}),
        }
        return err;
    };
    defer allocator.free(handler_source.code);

    // Build replay runtime config: keep replay_file_path set so Runtime
    // installs replay stubs instead of real virtual module functions.
    var replay_config = spec.runtime_config;
    replay_config.trace_file_path = null;
    // replay_file_path stays set to signal replay mode

    var summary = ReplaySummary{};
    var results: std.ArrayList(ReplayResult) = .empty;
    defer {
        for (results.items) |r| r.deinit(allocator);
        results.deinit(allocator);
    }

    std.log.info("Replaying {d} traces against {s}...\n", .{ groups.len, handler_source.filename });

    for (groups) |group| {
        const result = replayOne(
            allocator,
            replay_config,
            handler_source.code,
            handler_source.filename,
            &group,
        ) catch |err| {
            const failed_result = ReplayResult.fromReplayError(group, err);
            try results.append(allocator, failed_result);
            summary.record(failed_result);
            continue;
        };
        try results.append(allocator, result);
        summary.record(result);
    }

    printReplaySummary(handler_source.filename, summary);
    printReplayDiffs(results.items, summary);

    if (summary.identical == summary.total) {
        std.log.info("\nAll {d} traces passed.\n", .{summary.total});
        return;
    }
    return error.ReplayVerificationFailed;
}

/// Replay a single parsed trace group against an in-memory handler.
///
/// `config.replay_file_path` MUST be non-null - it is the sentinel that
/// makes `Runtime.init` install replay stubs for virtual modules instead
/// of real implementations. Any non-null string works (the path is not
/// re-read; `replayOne` operates on the supplied `handler_code` directly).
///
/// When `group.response` is null (the trace is a counterexample witness
/// rather than a recorded run), `match` returns `true` whenever the
/// handler executed without erroring and `actual_body_owned` carries an
/// owned copy of the response body so callers can apply their own
/// classifier (e.g. "did the secret sentinel appear?"). Caller owns the
/// returned `ReplayResult` and must call `deinit` on it.
pub fn replayOne(
    allocator: std.mem.Allocator,
    config: RuntimeConfig,
    handler_code: []const u8,
    handler_filename: []const u8,
    group: *const trace.RequestTraceGroup,
) !ReplayResult {
    // Create a fresh runtime for each replay.
    // Config has replay_file_path set, so Runtime.init registers replay stubs
    // for virtual modules and fetchSync instead of real implementations.
    const rt = try Runtime.init(allocator, config);
    defer rt.deinit();

    // Set up per-request replay state in module_state.
    // The replay stubs (generated by makeReplayStub) read from this.
    var replay_state = trace.ReplayState{
        .io_calls = group.io_calls,
        .cursor = 0,
        .divergences = 0,
    };
    rt.ctx.setModuleState(
        trace.REPLAY_STATE_SLOT,
        @ptrCast(&replay_state),
        &trace.ReplayState.deinitOpaque,
    );
    // Clear module_state before replay_state goes out of scope
    defer rt.ctx.module_state[trace.REPLAY_STATE_SLOT] = null;

    // Load handler code
    try rt.loadCode(handler_code, handler_filename);

    // Build request from trace
    var headers_list: std.ArrayListUnmanaged(HttpHeader) = .empty;
    defer headers_list.deinit(allocator);

    try parseHeadersFromJson(allocator, group.request.headers_json, &headers_list);

    // Unescape the request body (shared with test_runner) so a capsule decodes
    // identically under `--replay` and `--test`.
    const ub = trace.unescapeBody(allocator, group.request.body);
    defer if (ub.owned) |owned| allocator.free(owned);

    // Split req.path / req.query exactly as the live server and test_runner do,
    // so a capsule recorded from `GET /x?lat=52` replays with the same req.path
    // and req.query instead of a false regression on an unchanged handler.
    const target = runtime_natives.parseRequestTarget(allocator, group.request.url);
    defer target.deinit(allocator);

    const request = HttpRequestView{
        .method = group.request.method,
        .url = group.request.url,
        .path = target.path,
        .query_params = target.params,
        .headers = headers_list,
        .body = ub.slice,
    };

    // Execute handler
    var response = rt.executeHandler(request) catch |err| {
        return ReplayResult{
            .match = false,
            .expected_status = if (group.response) |r| r.status else 200,
            .actual_status = 0,
            .body_match = false,
            .expected_body_owned = &.{},
            .actual_body_owned = &.{},
            .io_divergences = replay_state.divergences,
            .io_total = @intCast(group.io_calls.len),
            .err = err,
        };
    };
    defer response.deinit();

    const expected = group.response orelse {
        // Witness case: no expected response was recorded. Hand back the
        // actual body so the caller can decide whether the violation
        // reproduced (e.g. a secret-leak classifier checks for the stub
        // sentinel string in the body).
        const body_copy = if (response.body.len == 0)
            &[_]u8{}
        else
            try allocator.dupe(u8, response.body);
        return ReplayResult{
            .match = true,
            .expected_status = 200,
            .actual_status = response.status,
            .body_match = true,
            .expected_body_owned = &.{},
            .actual_body_owned = body_copy,
            .io_divergences = replay_state.divergences,
            .io_total = @intCast(group.io_calls.len),
            .err = null,
        };
    };

    const status_match = response.status == expected.status;

    // The trace stores body as a JSON string value with escape sequences
    // like \" for embedded quotes. Unescape before comparing.
    const expected_unescaped = trace.unescapeJson(allocator, expected.body) catch &.{};
    const body_match = if (expected_unescaped.len > 0)
        std.mem.eql(u8, response.body, expected_unescaped)
    else
        std.mem.eql(u8, response.body, expected.body);

    // Dupe the actual body before response.deinit() frees it.
    // Keep the unescaped expected body for diff display (avoids re-unescaping).
    const body_copy = if (!body_match and response.body.len > 0 and response.body.len <= 200)
        allocator.dupe(u8, response.body) catch &.{}
    else
        &.{};

    // A faithful replay consumes every recorded I/O entry. Leftover entries mean
    // the edited handler dropped a recorded effect (e.g. a trailing cacheSet),
    // which must fail closed - otherwise a deleted side effect reads as
    // "reproduced".
    const leftover = replay_state.unconsumedCount();

    return ReplayResult{
        .match = status_match and body_match and replay_state.divergences == 0 and leftover == 0,
        .expected_status = expected.status,
        .actual_status = response.status,
        .body_match = body_match,
        .expected_body_owned = if (!body_match) expected_unescaped else blk: {
            if (expected_unescaped.len > 0) allocator.free(expected_unescaped);
            break :blk &.{};
        },
        .actual_body_owned = body_copy,
        .io_divergences = replay_state.divergences,
        .io_total = @intCast(group.io_calls.len),
        .err = null,
    };
}

// ============================================================================
// Result Types
// ============================================================================

pub const ReplayResult = struct {
    match: bool,
    expected_status: u16,
    actual_status: u16,
    body_match: bool,
    /// Owned unescaped expected body (for diff display). Empty if match.
    expected_body_owned: []const u8,
    /// Owned copy of the actual response body (for diff display). Empty if match.
    actual_body_owned: []const u8,
    io_divergences: u32,
    io_total: u32,
    err: ?anyerror,

    pub fn fromReplayError(group: trace.RequestTraceGroup, err: anyerror) ReplayResult {
        return .{
            .match = false,
            .expected_status = if (group.response) |response| response.status else 200,
            .actual_status = 0,
            .body_match = false,
            .expected_body_owned = &.{},
            .actual_body_owned = &.{},
            .io_divergences = 0,
            .io_total = @intCast(group.io_calls.len),
            .err = err,
        };
    }

    pub fn deinit(self: *const ReplayResult, allocator: std.mem.Allocator) void {
        if (self.expected_body_owned.len > 0) allocator.free(self.expected_body_owned);
        if (self.actual_body_owned.len > 0) allocator.free(self.actual_body_owned);
    }
};

pub const ReplaySummary = struct {
    total: u32 = 0,
    identical: u32 = 0,
    status_changed: u32 = 0,
    body_changed: u32 = 0,
    diverged: u32 = 0,

    pub fn record(self: *ReplaySummary, result: ReplayResult) void {
        self.total += 1;
        if (result.match) {
            self.identical += 1;
            return;
        }
        if (result.err != null) {
            self.diverged += 1;
            return;
        }
        if (result.expected_status != result.actual_status) {
            self.status_changed += 1;
            return;
        }
        if (!result.body_match) {
            self.body_changed += 1;
            return;
        }
        self.diverged += 1;
    }
};

// ============================================================================
// Helpers
// ============================================================================

fn readFile(allocator: std.mem.Allocator, path: []const u8) ![]const u8 {
    return zq.file_io.readFile(allocator, path, 100 * 1024 * 1024);
}

const LoadedTraceGroups = struct {
    source: []const u8,
    groups: []trace.RequestTraceGroup,

    fn deinit(self: *LoadedTraceGroups, allocator: std.mem.Allocator) void {
        freeTraceGroups(allocator, self.groups);
        allocator.free(self.source);
    }
};

fn loadTraceGroups(allocator: std.mem.Allocator, replay_path: []const u8) !LoadedTraceGroups {
    const trace_source = readFile(allocator, replay_path) catch |err| {
        if (!builtin.is_test) std.log.err("Failed to read trace file '{s}': {}", .{ replay_path, err });
        return err;
    };
    errdefer allocator.free(trace_source);

    return .{
        .source = trace_source,
        .groups = try trace.parseTraceFile(allocator, trace_source),
    };
}

fn freeTraceGroups(allocator: std.mem.Allocator, groups: []trace.RequestTraceGroup) void {
    for (groups) |group| allocator.free(group.io_calls);
    allocator.free(groups);
}

fn printReplaySummary(handler_filename: []const u8, summary: ReplaySummary) void {
    std.log.info("\nReplay results for {s}:\n", .{handler_filename});
    std.log.info("  {d}/{d} identical\n", .{ summary.identical, summary.total });
    if (summary.status_changed > 0) {
        std.log.info("  {d} status code changes\n", .{summary.status_changed});
    }
    if (summary.body_changed > 0) {
        std.log.info("  {d} body changes\n", .{summary.body_changed});
    }
    if (summary.diverged > 0) {
        std.log.info("  {d} diverged (I/O mismatch or runtime error)\n", .{summary.diverged});
    }
}

fn printReplayDiffs(results: []const ReplayResult, summary: ReplaySummary) void {
    var diff_count: u32 = 0;
    for (results, 0..) |result, idx| {
        if (result.match) continue;
        if (diff_count >= 10) {
            std.log.info("\n  ... and {d} more differences\n", .{summary.total - summary.identical - diff_count});
            break;
        }
        diff_count += 1;

        if (result.err) |err| {
            std.log.info("\nTrace #{d}: error - {}\n", .{ idx, err });
            continue;
        }

        if (result.expected_status != result.actual_status) {
            std.log.info("\nTrace #{d}: status changed {d} -> {d}\n", .{ idx, result.expected_status, result.actual_status });
        }
        if (!result.body_match) {
            std.log.info("\nTrace #{d}: body changed\n", .{idx});
            if (result.expected_body_owned.len > 0) {
                std.log.info("  - {s}\n", .{result.expected_body_owned});
            }
            if (result.actual_body_owned.len > 0) {
                std.log.info("  + {s}\n", .{result.actual_body_owned});
            }
        }
    }
}

const parseHeadersFromJson = @import("trace_helpers.zig").parseHeadersFromJson;

// ============================================================================
// Tests
// ============================================================================

const counterexample = zq.counterexample;

test "witness round-trip: solved witness replays into an executable leak" {
    // Proof the counterexample wire format is executable end-to-end.
    // We synthesise a witness for the secret-leak pattern, serialise it
    // through counterexample.writeJsonl, parse it back with the trace
    // parser, and replay it against the handler under the runtime's
    // standard replay stubs. The response body MUST contain the sentinel
    // secret string that the solver places in the env stub - that is the
    // witness actually driving the handler into the leaking branch.
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const handler_code =
        \\import { env } from "zttp:env";
        \\function handler(req) {
        \\  const secret = env("SECRET_KEY");
        \\  if (secret) {
        \\    return Response.json({ leaked: secret });
        \\  }
        \\  return Response.json({ ok: true });
        \\}
    ;

    // 1. Synthesise a witness with the constraint + io-call shape that
    // flow_checker would attach to a secret_in_response diagnostic.
    const constraints = [_]counterexample.WitnessConstraint{
        .{ .stub_truthy = .{
            .module = "env",
            .func = "env",
            .returns = .optional_string,
        } },
    };
    const io_calls = [_]counterexample.TrackedIoCall{
        .{ .module = "env", .func = "env", .returns = .optional_string },
    };
    var witness = try counterexample.solve(allocator, .{
        .property = .no_secret_leakage,
        .origin = .{ .line = 3, .column = 18 },
        .sink = .{ .line = 5, .column = 12 },
        .summary = "SECRET_KEY flows into Response body",
        .constraints = &constraints,
        .io_calls = &io_calls,
    });
    defer witness.deinit(allocator);

    // 2. Serialise as JSONL exactly as agents would emit it.
    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(allocator);
    var aw: std.Io.Writer.Allocating = .fromArrayList(allocator, &buf);
    try counterexample.writeJsonl(&aw.writer, witness);
    buf = aw.toArrayList();

    // 3. Parse the JSONL. The trace parser silently drops the `witness`
    // header line (unknown type), consuming only the request + io lines.
    const groups = try zq.trace.parseTraceFile(allocator, buf.items);
    defer {
        for (groups) |g| allocator.free(g.io_calls);
        allocator.free(groups);
    }
    try std.testing.expectEqual(@as(usize, 1), groups.len);
    const group = groups[0];
    try std.testing.expectEqualStrings("GET", group.request.method);
    try std.testing.expectEqual(@as(usize, 1), group.io_calls.len);
    try std.testing.expectEqualStrings("env", group.io_calls[0].func);

    // 4. Create a runtime in replay mode so the virtual-module calls get
    // redirected to the replay stubs that consume ReplayState.
    const rt = try Runtime.init(allocator, .{ .replay_file_path = "witness-roundtrip-test" });
    defer rt.deinit();

    var replay_state = zq.trace.ReplayState{
        .io_calls = group.io_calls,
        .cursor = 0,
        .divergences = 0,
    };
    rt.ctx.setModuleState(
        zq.trace.REPLAY_STATE_SLOT,
        @ptrCast(&replay_state),
        &zq.trace.ReplayState.deinitOpaque,
    );
    defer rt.ctx.module_state[zq.trace.REPLAY_STATE_SLOT] = null;

    // 5. Load handler and execute the request built from the witness.
    try rt.loadCode(handler_code, "<witness-roundtrip>");

    var headers: std.ArrayListUnmanaged(HttpHeader) = .empty;
    defer headers.deinit(allocator);
    try parseHeadersFromJson(allocator, group.request.headers_json, &headers);

    const request = HttpRequestView{
        .method = group.request.method,
        .url = group.request.url,
        .headers = headers,
        .body = group.request.body,
    };

    var response = try rt.executeHandler(request);
    defer response.deinit();

    // 6. The handler took the leaking branch. The response body carries
    // the sentinel that counterexample.stubValue plants for optional_string
    // returns: "secret-sentinel". No divergences on the stub consumption.
    try std.testing.expectEqual(@as(u16, 200), response.status);
    try std.testing.expect(
        std.mem.indexOf(u8, response.body, "secret-sentinel") != null,
    );
    try std.testing.expectEqual(@as(u32, 0), replay_state.divergences);
}

// Build a replay runtime, install a single recorded crypto.sha256 entry, run a
// handler that hashes `live_arg`, and return the resulting divergence count.
fn replaySha256ArgDivergences(allocator: std.mem.Allocator, comptime live_arg: []const u8) !u32 {
    const handler_code =
        "import { sha256 } from \"zttp:crypto\";\n" ++
        "function handler(req) {\n" ++
        "  return Response.json({ h: sha256(\"" ++ live_arg ++ "\") });\n" ++
        "}\n";

    const rt = try Runtime.init(allocator, .{ .replay_file_path = "argcheck-test" });
    defer rt.deinit();

    // Recording captured the call with the argument "AAA".
    const io_calls = [_]trace.IoEntry{
        .{ .seq = 0, .module = "crypto", .func = "sha256", .args_json = "[\"AAA\"]", .result_json = "\"deadbeef\"" },
    };
    var replay_state = trace.ReplayState{ .io_calls = &io_calls, .cursor = 0, .divergences = 0 };
    rt.ctx.setModuleState(
        trace.REPLAY_STATE_SLOT,
        @ptrCast(&replay_state),
        &trace.ReplayState.deinitOpaque,
    );
    defer rt.ctx.module_state[trace.REPLAY_STATE_SLOT] = null;

    try rt.loadCode(handler_code, "<argcheck>");

    var headers: std.ArrayListUnmanaged(HttpHeader) = .empty;
    defer headers.deinit(allocator);
    const request = HttpRequestView{ .method = "GET", .url = "/", .headers = headers, .body = null };

    var response = try rt.executeHandler(request);
    defer response.deinit();
    try std.testing.expectEqual(@as(u16, 200), response.status);
    return replay_state.divergences;
}

test "replay flags an argument change at the matched path (#5)" {
    // The recording captured sha256("AAA"); the replayed handler calls
    // sha256("BBB"). The stub still matches on module+func and returns the
    // recorded result, but the matched-path arg check must count a divergence so
    // replay verification fails closed on the behavior change.
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    try std.testing.expect(try replaySha256ArgDivergences(arena.allocator(), "BBB") > 0);
}

test "replay does not flag matching arguments (#5 control)" {
    // Same recording, handler calls sha256 with the recorded "AAA": no drift.
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    try std.testing.expectEqual(@as(u32, 0), try replaySha256ArgDivergences(arena.allocator(), "AAA"));
}

const replay_exit_test_trace =
    \\{"type":"request","method":"GET","url":"/","headers":{},"body":null}
    \\{"type":"response","status":200,"headers":{},"body":"{\"ok\":true}"}
    \\{"type":"meta","duration_us":1,"handler":"handler.ts","pool_slot":0,"io_count":0}
;

const replay_mismatch_and_error_trace =
    \\{"type":"request","method":"GET","url":"/mismatch","headers":{},"body":null}
    \\{"type":"response","status":200,"headers":{},"body":"{\"ok\":true}"}
    \\{"type":"meta","duration_us":1,"handler":"handler.ts","pool_slot":0,"io_count":0}
    \\{"type":"request","method":"GET","url":"/error","headers":{},"body":null}
    \\{"type":"response","status":200,"headers":{},"body":"{\"ok\":true}"}
    \\{"type":"meta","duration_us":1,"handler":"handler.ts","pool_slot":0,"io_count":0}
;

fn replayExitTestPath(allocator: std.mem.Allocator, tmp: *std.testing.TmpDir) ![]u8 {
    var root_buf: [std.fs.max_path_bytes]u8 = undefined;
    const root_len = try tmp.dir.realPath(std.testing.io, &root_buf);
    return std.fs.path.join(allocator, &.{ root_buf[0..root_len], "trace.jsonl" });
}

test "replay mismatch returns verification failure" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "trace.jsonl", .data = replay_exit_test_trace });
    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code = "function handler(req) { return Response.json({ ok: false }); }" },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try std.testing.expectError(error.ReplayVerificationFailed, run(allocator, spec));
}

test "replay rejects a malformed trace line" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "trace.jsonl", .data = "not json\n" });
    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code = "function handler(req) { return Response.json({ ok: true }); }" },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try std.testing.expectError(error.InvalidTraceJson, run(allocator, spec));
}

test "replay rejects an unknown trace entry type" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const fixture =
        \\{"type":"request","method":"GET","url":"/","headers":{},"body":null}
        \\{"type":"respones","status":200,"headers":{},"body":"ok"}
        \\{"type":"meta","duration_us":1,"handler":"handler.ts","pool_slot":0,"io_count":0}
    ;
    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "trace.jsonl", .data = fixture });
    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code = "function handler(req) { return Response.json({ ok: true }); }" },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try std.testing.expectError(error.InvalidTraceEntry, run(allocator, spec));
}

test "replay rejects a truncated response-less trace" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const fixture =
        \\{"type":"request","method":"GET","url":"/","headers":{},"body":null}
        \\{"type":"meta","duration_us":1,"handler":"handler.ts","pool_slot":0,"io_count":0}
    ;
    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "trace.jsonl", .data = fixture });
    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code = "function handler(req) { return Response.json({ ok: true }); }" },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try std.testing.expectError(error.InvalidTraceEntry, run(allocator, spec));
}

test "replay rejects a zero-trace fixture" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "trace.jsonl", .data = "" });
    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code = "function handler(req) { return Response.json({ ok: true }); }" },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try std.testing.expectError(error.InvalidReplayFixture, run(allocator, spec));
}

test "replay trace errors and mismatches are verification failures" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "trace.jsonl", .data = replay_mismatch_and_error_trace });
    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code =
        \\function handler(req) {
        \\  if (req.path === "/error") return missing();
        \\  return Response.json({ ok: false });
        \\}
        },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try std.testing.expectError(error.ReplayVerificationFailed, run(allocator, spec));
}

test "replay hard error stays distinct from verification failure" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code = "function handler(req) { return Response.json({ ok: true }); }" },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try std.testing.expectError(error.FileNotFound, run(allocator, spec));
}

test "all-identical replay returns success" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "trace.jsonl", .data = replay_exit_test_trace });
    const trace_path = try replayExitTestPath(allocator, &tmp);
    const spec = ExecutionSpec{
        .handler = .{ .inline_code = "function handler(req) { return Response.json({ ok: true }); }" },
        .runtime_config = .{ .replay_file_path = trace_path },
    };

    try run(allocator, spec);
}
