//! TypeScript SDK generator.
//!
//! Emits a dependency-free TypeScript client from compiler-proven API facts in
//! HandlerContract. Only routes and schemas that can be represented without
//! guessing receive typed helpers; everything else is recorded in
//! skippedOperations and remains accessible through requestRaw().
//!
//! Routes with a single response code emit Promise<TypedResponse<T>>.
//! Routes with multiple response codes emit a discriminated union:
//!   Promise<{ status: 200; data: T; response: Response } | { status: 404; data: E; response: Response }>
//! allowing TypeScript callers to narrow on .status.

const std = @import("std");
const handler_contract = @import("zts").handler_contract;

const HandlerContract = @import("zts").HandlerContract;
const ApiRouteInfo = handler_contract.ApiRouteInfo;
const ApiSchemaInfo = handler_contract.ApiSchemaInfo;
const ApiParamInfo = handler_contract.ApiParamInfo;

pub const RenderOptions = struct {};

const SchemaAlias = struct {
    source_name: []const u8,
    type_name: []const u8,
};

const InlineAlias = struct {
    route_index: usize,
    type_name: []const u8, // owned
    /// Non-null for union arm types. Borrowed from the source ApiResponseInfo.
    schema_json_override: ?[]const u8 = null,
};

/// One arm of a multi-response discriminated union.
const UnionArm = struct {
    status: u16,
    type_name: []const u8,
};

const RoutePlan = struct {
    route_index: usize,
    method_name: []const u8,
    request_type_name: ?[]const u8,
    request_content_type: ?[]const u8 = null,
    /// Null when response_union is set.
    response_type_name: ?[]const u8,
    /// Non-null for routes with multiple response codes; owned slice.
    response_union: ?[]UnionArm = null,
};

const SkippedOperation = struct {
    route_index: usize,
    reason: []const u8,
};

const TypeEmitError = error{
    UnsupportedSchema,
};

pub fn writeTypeScriptClient(
    writer: anytype,
    allocator: std.mem.Allocator,
    contract: *const HandlerContract,
    _: RenderOptions,
) !void {
    var schema_aliases: std.ArrayList(SchemaAlias) = .empty;
    defer freeSchemaAliases(&schema_aliases, allocator);

    var inline_aliases: std.ArrayList(InlineAlias) = .empty;
    defer freeInlineAliases(&inline_aliases, allocator);

    var route_plans: std.ArrayList(RoutePlan) = .empty;
    defer freeRoutePlans(&route_plans, allocator);

    var skipped: std.ArrayList(SkippedOperation) = .empty;
    defer freeSkipped(&skipped, allocator);

    try buildSchemaAliases(allocator, contract, &schema_aliases);
    try buildRoutePlans(allocator, contract, &schema_aliases, &inline_aliases, &route_plans, &skipped);

    try writer.writeAll("// Generated by zttp. Do not edit by hand.\n");
    try writer.writeAll("// This client only exposes operations and types the compiler could prove.\n\n");
    try writer.writeAll("export type ClientConfig = {\n");
    try writer.writeAll("  baseUrl: string;\n");
    try writer.writeAll("  fetch?: typeof fetch;\n");
    try writer.writeAll("  headers?: HeadersInit;\n");
    try writer.writeAll("};\n\n");
    try writer.writeAll("export type RequestOptions = {\n");
    try writer.writeAll("  headers?: HeadersInit;\n");
    try writer.writeAll("  signal?: AbortSignal;\n");
    try writer.writeAll("};\n\n");
    try writer.writeAll("export type RawRequestInit = RequestOptions & {\n");
    try writer.writeAll("  body?: BodyInit | null;\n");
    try writer.writeAll("};\n\n");
    try writer.writeAll("export type TypedResponse<T> = {\n");
    try writer.writeAll("  status: number;\n");
    try writer.writeAll("  data: T;\n");
    try writer.writeAll("  response: Response;\n");
    try writer.writeAll("};\n\n");

    for (schema_aliases.items) |alias| {
        if (!std.mem.eql(u8, alias.source_name, alias.type_name)) {
            try writer.writeAll("// schema: ");
            try writer.writeAll(alias.source_name);
            try writer.writeByte('\n');
        }
        try writer.writeAll("export type ");
        try writer.writeAll(alias.type_name);
        try writer.writeAll(" = ");
        const schema = findSchema(contract.api.schemas.items, alias.source_name) orelse return error.UnsupportedSchema;
        try emitSchemaType(writer, allocator, schema.schema_json, 0);
        try writer.writeAll(";\n\n");
    }

    for (inline_aliases.items) |alias| {
        const schema_json = if (alias.schema_json_override) |sj| sj else contract.api.routes.items[alias.route_index].response_schema_json.?;
        try writer.writeAll("export type ");
        try writer.writeAll(alias.type_name);
        try writer.writeAll(" = ");
        try emitSchemaType(writer, allocator, schema_json, 0);
        try writer.writeAll(";\n\n");
    }

    try writer.writeAll("export const skippedOperations = [\n");
    for (skipped.items) |item| {
        const route = contract.api.routes.items[item.route_index];
        try writer.writeAll("  {\n");
        try writer.writeAll("    method: ");
        try writeTsString(writer, route.method);
        try writer.writeAll(",\n");
        try writer.writeAll("    path: ");
        try writeTsString(writer, route.path);
        try writer.writeAll(",\n");
        try writer.writeAll("    reason: ");
        try writeTsString(writer, item.reason);
        try writer.writeAll(",\n");
        try writer.writeAll("  },\n");
    }
    try writer.writeAll("] as const;\n\n");

    try writer.writeAll("function stripTrailingSlash(value: string): string {\n");
    try writer.writeAll("  return value.endsWith(\"/\") ? value.slice(0, -1) : value;\n");
    try writer.writeAll("}\n\n");
    try writer.writeAll("function mergeHeaders(baseHeaders?: HeadersInit, localHeaders?: HeadersInit): Headers {\n");
    try writer.writeAll("  const headers = new Headers(baseHeaders);\n");
    try writer.writeAll("  if (localHeaders) {\n");
    try writer.writeAll("    new Headers(localHeaders).forEach((value, key) => headers.set(key, value));\n");
    try writer.writeAll("  }\n");
    try writer.writeAll("  return headers;\n");
    try writer.writeAll("}\n\n");
    try writer.writeAll("function appendQueryString(path: string, query?: Record<string, string | number | boolean | undefined>): string {\n");
    try writer.writeAll("  if (!query) return path;\n");
    try writer.writeAll("  const params = new URLSearchParams();\n");
    try writer.writeAll("  for (const [key, value] of Object.entries(query)) {\n");
    try writer.writeAll("    if (value !== undefined) params.append(key, String(value));\n");
    try writer.writeAll("  }\n");
    try writer.writeAll("  const search = params.toString();\n");
    try writer.writeAll("  return search.length > 0 ? `${path}?${search}` : path;\n");
    try writer.writeAll("}\n\n");

    try writer.writeAll("export function createClient(config: ClientConfig) {\n");
    try writer.writeAll("  const baseUrl = stripTrailingSlash(config.baseUrl);\n");
    try writer.writeAll("  const fetchImpl = config.fetch ?? globalThis.fetch;\n\n");
    try writer.writeAll("  async function requestRaw(method: string, path: string, init: RawRequestInit = {}): Promise<Response> {\n");
    try writer.writeAll("    const headers = mergeHeaders(config.headers, init.headers);\n");
    try writer.writeAll("    const url = path.startsWith(\"/\") ? `${baseUrl}${path}` : `${baseUrl}/${path}`;\n");
    try writer.writeAll("    return fetchImpl(url, {\n");
    try writer.writeAll("      method,\n");
    try writer.writeAll("      headers,\n");
    try writer.writeAll("      body: init.body,\n");
    try writer.writeAll("      signal: init.signal,\n");
    try writer.writeAll("    });\n");
    try writer.writeAll("  }\n\n");

    try writer.writeAll("  return {\n");
    try writer.writeAll("    requestRaw");

    for (route_plans.items) |plan| {
        const route = contract.api.routes.items[plan.route_index];
        try writer.writeAll(",\n");
        if (route.requires_bearer or route.requires_jwt) {
            try writer.writeAll("    /** Proven contract requires bearer authentication. */\n");
        }
        try writer.writeAll("    async ");
        try writer.writeAll(plan.method_name);
        try writer.writeByte('(');
        try writeMethodArgs(writer, route, plan.request_type_name);
        if (plan.response_union) |arms| {
            try writer.writeAll("): Promise<\n");
            for (arms, 0..) |arm, i| {
                if (i > 0) {
                    try writer.writeAll("\n      | ");
                } else {
                    try writer.writeAll("      ");
                }
                try writer.print("{{ status: {d}; data: {s}; response: Response }}", .{ arm.status, arm.type_name });
            }
            try writer.writeAll("\n    > {\n");
        } else {
            try writer.writeAll("): Promise<TypedResponse<");
            try writer.writeAll(plan.response_type_name.?);
            try writer.writeAll(">> {\n");
        }
        try writer.writeAll("      const input = args ?? {};\n");
        try writer.writeAll("      const headers = mergeHeaders(undefined, input.headers);\n");
        if (plan.request_content_type) |content_type| {
            try writer.writeAll("      if (!headers.has(\"content-type\")) headers.set(\"content-type\", ");
            try writeTsString(writer, content_type);
            try writer.writeAll(");\n");
        }
        try writer.writeAll("      const response = await requestRaw(");
        try writeTsString(writer, route.method);
        try writer.writeAll(", ");
        try writeRequestPath(writer, route);
        try writer.writeAll(", {\n");
        try writer.writeAll("        headers,\n");
        if (plan.request_content_type) |content_type| {
            if (std.mem.eql(u8, content_type, "application/x-www-form-urlencoded")) {
                try writer.writeAll("        body: new URLSearchParams(Object.entries(input.body).flatMap(([key, value]) => value === undefined ? [] : [[key, String(value)]] as [string, string][])).toString(),\n");
            } else {
                try writer.writeAll("        body: JSON.stringify(input.body),\n");
            }
        } else {
            try writer.writeAll("        body: undefined,\n");
        }
        try writer.writeAll("        signal: input.signal,\n");
        try writer.writeAll("      });\n");
        if (plan.response_union != null) {
            try writer.writeAll("      const data = await response.json();\n");
            try writer.writeAll("      return { status: response.status, data, response } as any;\n");
        } else {
            try writer.writeAll("      const data = (await response.json()) as ");
            try writer.writeAll(plan.response_type_name.?);
            try writer.writeAll(";\n");
            try writer.writeAll("      return { status: response.status, data, response };\n");
        }
        try writer.writeAll("    }");
    }

    try writer.writeAll("\n  };\n");
    try writer.writeAll("}\n\n");
    try writer.writeAll("export type ApiClient = ReturnType<typeof createClient>;\n");
}

fn buildSchemaAliases(
    allocator: std.mem.Allocator,
    contract: *const HandlerContract,
    aliases: *std.ArrayList(SchemaAlias),
) !void {
    var used_names: std.ArrayList([]const u8) = .empty;
    defer freeStringList(&used_names, allocator);

    for (contract.api.schemas.items) |schema| {
        var parsed = try parsedSchema(allocator, schema.schema_json);
        parsed.deinit();
        var type_name = try sanitizeTypeName(allocator, schema.name);
        errdefer allocator.free(type_name);
        try uniquifyOwnedName(allocator, &used_names, &type_name);
        try aliases.append(allocator, .{
            .source_name = schema.name,
            .type_name = type_name,
        });
    }
}

fn buildRoutePlans(
    allocator: std.mem.Allocator,
    contract: *const HandlerContract,
    schema_aliases: *const std.ArrayList(SchemaAlias),
    inline_aliases: *std.ArrayList(InlineAlias),
    route_plans: *std.ArrayList(RoutePlan),
    skipped: *std.ArrayList(SkippedOperation),
) !void {
    const RequestInfo = struct {
        type_name: ?[]const u8 = null,
        content_type: ?[]const u8 = null,
    };

    var used_method_names: std.ArrayList([]const u8) = .empty;
    defer freeStringList(&used_method_names, allocator);

    var used_type_names: std.ArrayList([]const u8) = .empty;
    defer freeStringList(&used_type_names, allocator);

    for (schema_aliases.items) |alias| {
        try used_type_names.append(allocator, try allocator.dupe(u8, alias.type_name));
    }

    for (contract.api.routes.items, 0..) |route, idx| {
        if (route.query_params_dynamic) {
            try appendSkipped(skipped, allocator, idx, "query params are dynamic");
            continue;
        }
        if (route.header_params_dynamic) {
            try appendSkipped(skipped, allocator, idx, "header params are dynamic");
            continue;
        }

        const request_info = blk: {
            if (route.request_bodies_dynamic or route.request_schema_dynamic) {
                try appendSkipped(skipped, allocator, idx, "request schema is dynamic");
                continue;
            }
            if (route.request_bodies.items.len == 0) {
                if (route.request_schema_refs.items.len > 1) {
                    try appendSkipped(skipped, allocator, idx, "multiple request schemas are not supported");
                    continue;
                }
                if (route.request_schema_refs.items.len == 0) {
                    break :blk RequestInfo{};
                }
                const alias = findSchemaAlias(schema_aliases.items, route.request_schema_refs.items[0]) orelse {
                    try appendSkipped(skipped, allocator, idx, "request schema is not representable as TypeScript");
                    continue;
                };
                break :blk RequestInfo{ .type_name = alias.type_name };
            }
            if (route.request_bodies.items.len > 1) {
                try appendSkipped(skipped, allocator, idx, "multiple request bodies are not supported");
                continue;
            }
            const body = route.request_bodies.items[0];
            if (body.schema.isDynamic()) {
                try appendSkipped(skipped, allocator, idx, "request body is dynamic");
                continue;
            }
            const content_type = body.content_type orelse {
                try appendSkipped(skipped, allocator, idx, "request body content type is not proven");
                continue;
            };
            if (!std.mem.eql(u8, content_type, "application/json") and
                !std.mem.eql(u8, content_type, "application/x-www-form-urlencoded"))
            {
                try appendSkipped(skipped, allocator, idx, "request body content type is not supported");
                continue;
            }
            if (body.schema.schemaRef()) |schema_ref| {
                const alias = findSchemaAlias(schema_aliases.items, schema_ref) orelse {
                    try appendSkipped(skipped, allocator, idx, "request schema is not representable as TypeScript");
                    continue;
                };
                break :blk RequestInfo{ .type_name = alias.type_name, .content_type = body.content_type };
            }
            try appendSkipped(skipped, allocator, idx, "request schema is not proven");
            continue;
        };

        if (route.responses_dynamic or route.response_schema_dynamic) {
            try appendSkipped(skipped, allocator, idx, "response schema is dynamic");
            continue;
        }
        if (route.responses.items.len == 0) {
            if (route.response_content_type == null or !std.mem.eql(u8, route.response_content_type.?, "application/json")) {
                try appendSkipped(skipped, allocator, idx, "response is not proven JSON");
                continue;
            }

            const response_type_name = blk: {
                if (route.response_schema_ref) |schema_ref| {
                    const alias = findSchemaAlias(schema_aliases.items, schema_ref) orelse {
                        try appendSkipped(skipped, allocator, idx, "response schema is not representable as TypeScript");
                        continue;
                    };
                    break :blk alias.type_name;
                }
                if (route.response_schema_json) |schema_json| {
                    var parsed = parsedSchema(allocator, schema_json) catch {
                        try appendSkipped(skipped, allocator, idx, "response schema is not representable as TypeScript");
                        continue;
                    };
                    parsed.deinit();
                    const base_inline_name = try baseInlineResponseName(allocator, route);
                    defer allocator.free(base_inline_name);
                    var inline_name = try sanitizeTypeName(allocator, base_inline_name);
                    try uniquifyOwnedName(allocator, &used_type_names, &inline_name);
                    try inline_aliases.append(allocator, .{
                        .route_index = idx,
                        .type_name = inline_name,
                    });
                    break :blk inline_aliases.items[inline_aliases.items.len - 1].type_name;
                }
                try appendSkipped(skipped, allocator, idx, "response schema is not proven");
                continue;
            };

            var method_name = try methodNameForRoute(allocator, route);
            errdefer allocator.free(method_name);
            try uniquifyOwnedName(allocator, &used_method_names, &method_name);

            try route_plans.append(allocator, .{
                .route_index = idx,
                .method_name = method_name,
                .request_type_name = request_info.type_name,
                .request_content_type = request_info.content_type,
                .response_type_name = response_type_name,
            });
            continue;
        }
        if (route.responses.items.len > 1) {
            // Multi-response: build a discriminated union, one arm per status code.
            var arms: std.ArrayList(UnionArm) = .empty;
            var skip_reason: ?[]const u8 = null;

            for (route.responses.items) |response| {
                if (skip_reason != null) break;
                if (response.schema.isDynamic()) {
                    skip_reason = "response schema is dynamic";
                    break;
                }
                const ct = response.content_type orelse {
                    skip_reason = "response is not proven JSON";
                    break;
                };
                if (!std.mem.eql(u8, ct, "application/json")) {
                    skip_reason = "response is not proven JSON";
                    break;
                }
                const status = response.status orelse 200;
                const arm_type_name: []const u8 = arm_blk: {
                    if (response.schema.schemaRef()) |schema_ref| {
                        const alias = findSchemaAlias(schema_aliases.items, schema_ref) orelse {
                            skip_reason = "response schema is not representable as TypeScript";
                            break :arm_blk "";
                        };
                        break :arm_blk alias.type_name;
                    }
                    if (response.schema.schemaJson()) |schema_json| {
                        var parsed = parsedSchema(allocator, schema_json) catch {
                            skip_reason = "response schema is not representable as TypeScript";
                            break :arm_blk "";
                        };
                        parsed.deinit();
                        const base_name = try baseInlineResponseNameWithStatus(allocator, route, status);
                        defer allocator.free(base_name);
                        var inline_name = try sanitizeTypeName(allocator, base_name);
                        try uniquifyOwnedName(allocator, &used_type_names, &inline_name);
                        try inline_aliases.append(allocator, .{
                            .route_index = idx,
                            .type_name = inline_name,
                            .schema_json_override = schema_json,
                        });
                        break :arm_blk inline_aliases.items[inline_aliases.items.len - 1].type_name;
                    }
                    skip_reason = "response schema is not proven";
                    break :arm_blk "";
                };
                if (skip_reason == null) try arms.append(allocator, .{ .status = status, .type_name = arm_type_name });
            }

            if (skip_reason) |reason| {
                arms.deinit(allocator);
                try appendSkipped(skipped, allocator, idx, reason);
                continue;
            }

            var method_name = try methodNameForRoute(allocator, route);
            errdefer allocator.free(method_name);
            try uniquifyOwnedName(allocator, &used_method_names, &method_name);
            const arms_slice = try arms.toOwnedSlice(allocator);
            try route_plans.append(allocator, .{
                .route_index = idx,
                .method_name = method_name,
                .request_type_name = request_info.type_name,
                .request_content_type = request_info.content_type,
                .response_type_name = null,
                .response_union = arms_slice,
            });
            continue;
        }
        const response = route.responses.items[0];
        if (response.schema.isDynamic()) {
            try appendSkipped(skipped, allocator, idx, "response schema is dynamic");
            continue;
        }
        if (response.content_type == null or !std.mem.eql(u8, response.content_type.?, "application/json")) {
            try appendSkipped(skipped, allocator, idx, "response is not proven JSON");
            continue;
        }

        const response_type_name = blk: {
            if (response.schema.schemaRef()) |schema_ref| {
                const alias = findSchemaAlias(schema_aliases.items, schema_ref) orelse {
                    try appendSkipped(skipped, allocator, idx, "response schema is not representable as TypeScript");
                    continue;
                };
                break :blk alias.type_name;
            }
            if (response.schema.schemaJson()) |schema_json| {
                var parsed = parsedSchema(allocator, schema_json) catch {
                    try appendSkipped(skipped, allocator, idx, "response schema is not representable as TypeScript");
                    continue;
                };
                parsed.deinit();
                const base_inline_name = try baseInlineResponseName(allocator, route);
                defer allocator.free(base_inline_name);
                var inline_name = try sanitizeTypeName(allocator, base_inline_name);
                try uniquifyOwnedName(allocator, &used_type_names, &inline_name);
                try inline_aliases.append(allocator, .{
                    .route_index = idx,
                    .type_name = inline_name,
                });
                break :blk inline_aliases.items[inline_aliases.items.len - 1].type_name;
            }
            try appendSkipped(skipped, allocator, idx, "response schema is not proven");
            continue;
        };

        var method_name = try methodNameForRoute(allocator, route);
        errdefer allocator.free(method_name);
        try uniquifyOwnedName(allocator, &used_method_names, &method_name);

        try route_plans.append(allocator, .{
            .route_index = idx,
            .method_name = method_name,
            .request_type_name = request_info.type_name,
            .request_content_type = request_info.content_type,
            .response_type_name = response_type_name,
        });
    }
}

fn appendRouteNamePrefix(allocator: std.mem.Allocator, out: *std.ArrayList(u8), route: ApiRouteInfo) !void {
    const method = try titleCaseSegment(allocator, route.method);
    defer allocator.free(method);
    try out.appendSlice(allocator, method);

    if (std.mem.eql(u8, route.path, "/")) {
        try out.appendSlice(allocator, "Root");
    } else {
        var start: usize = 0;
        while (start < route.path.len) {
            while (start < route.path.len and route.path[start] == '/') : (start += 1) {}
            if (start >= route.path.len) break;
            var end = start;
            while (end < route.path.len and route.path[end] != '/') : (end += 1) {}
            const segment = route.path[start..end];
            const cleaned = if (segment.len > 0 and segment[0] == ':') segment[1..] else segment;
            const titled = try titleCaseSegment(allocator, cleaned);
            defer allocator.free(titled);
            try out.appendSlice(allocator, titled);
            start = end;
        }
    }
}

fn baseInlineResponseName(allocator: std.mem.Allocator, route: ApiRouteInfo) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    try appendRouteNamePrefix(allocator, &out, route);
    try out.appendSlice(allocator, "Response");
    return out.toOwnedSlice(allocator);
}

/// Appends the HTTP status code before "Response", e.g. "GetUsersId200Response".
fn baseInlineResponseNameWithStatus(allocator: std.mem.Allocator, route: ApiRouteInfo, status: u16) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    try appendRouteNamePrefix(allocator, &out, route);
    var status_buf: [5]u8 = undefined;
    const status_str = std.fmt.bufPrint(&status_buf, "{d}", .{status}) catch "0";
    try out.appendSlice(allocator, status_str);
    try out.appendSlice(allocator, "Response");
    return out.toOwnedSlice(allocator);
}

fn freeSchemaAliases(list: *std.ArrayList(SchemaAlias), allocator: std.mem.Allocator) void {
    for (list.items) |alias| allocator.free(alias.type_name);
    list.deinit(allocator);
}

fn freeInlineAliases(list: *std.ArrayList(InlineAlias), allocator: std.mem.Allocator) void {
    for (list.items) |alias| allocator.free(alias.type_name);
    list.deinit(allocator);
}

fn freeRoutePlans(list: *std.ArrayList(RoutePlan), allocator: std.mem.Allocator) void {
    for (list.items) |plan| {
        allocator.free(plan.method_name);
        if (plan.response_union) |arms| allocator.free(arms);
    }
    list.deinit(allocator);
}

fn freeSkipped(list: *std.ArrayList(SkippedOperation), allocator: std.mem.Allocator) void {
    for (list.items) |item| allocator.free(item.reason);
    list.deinit(allocator);
}

fn freeStringList(list: *std.ArrayList([]const u8), allocator: std.mem.Allocator) void {
    for (list.items) |value| allocator.free(value);
    list.deinit(allocator);
}

fn appendSkipped(
    skipped: *std.ArrayList(SkippedOperation),
    allocator: std.mem.Allocator,
    route_index: usize,
    reason: []const u8,
) !void {
    try skipped.append(allocator, .{
        .route_index = route_index,
        .reason = try allocator.dupe(u8, reason),
    });
}

fn findSchema(schemas: []const ApiSchemaInfo, name: []const u8) ?ApiSchemaInfo {
    for (schemas) |schema| {
        if (std.mem.eql(u8, schema.name, name)) return schema;
    }
    return null;
}

fn findSchemaAlias(aliases: []const SchemaAlias, source_name: []const u8) ?SchemaAlias {
    for (aliases) |alias| {
        if (std.mem.eql(u8, alias.source_name, source_name)) return alias;
    }
    return null;
}

fn parsedSchema(allocator: std.mem.Allocator, schema_json: []const u8) !std.json.Parsed(std.json.Value) {
    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, schema_json, .{});
    errdefer parsed.deinit();
    try validateSchemaValue(parsed.value);
    return parsed;
}

fn validateSchemaValue(value: std.json.Value) TypeEmitError!void {
    switch (value) {
        .object => |obj| {
            if (obj.get("type")) |type_val| {
                switch (type_val) {
                    .string => |kind| {
                        if (std.mem.eql(u8, kind, "string") or
                            std.mem.eql(u8, kind, "number") or
                            std.mem.eql(u8, kind, "boolean"))
                        {
                            if (obj.get("enum")) |enum_val| try validateEnumValues(enum_val, kind);
                            if (obj.get("const")) |const_val| try validateConstValue(const_val, kind);
                            return;
                        }
                        if (std.mem.eql(u8, kind, "object")) {
                            if (obj.get("properties")) |props| try validateProperties(props);
                            if (obj.get("required")) |required| try validateRequired(required);
                            return;
                        }
                        if (std.mem.eql(u8, kind, "array")) {
                            if (obj.get("prefixItems")) |prefix_items| {
                                if (obj.get("items")) |items| switch (items) {
                                    .bool => |flag| if (flag) return TypeEmitError.UnsupportedSchema,
                                    else => return TypeEmitError.UnsupportedSchema,
                                };
                                try validatePrefixItems(prefix_items);
                                return;
                            }
                            const items = obj.get("items") orelse return TypeEmitError.UnsupportedSchema;
                            try validateSchemaValue(items);
                            return;
                        }
                    },
                    else => return TypeEmitError.UnsupportedSchema,
                }
            }
            if (obj.get("const")) |const_val| {
                try validateLiteralValue(const_val);
                return;
            }
            return TypeEmitError.UnsupportedSchema;
        },
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn validateProperties(value: std.json.Value) TypeEmitError!void {
    switch (value) {
        .object => |obj| {
            var it = obj.iterator();
            while (it.next()) |entry| try validateSchemaValue(entry.value_ptr.*);
        },
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn validateRequired(value: std.json.Value) TypeEmitError!void {
    switch (value) {
        .array => |array| {
            for (array.items) |item| {
                if (item != .string) return TypeEmitError.UnsupportedSchema;
            }
        },
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn validatePrefixItems(value: std.json.Value) TypeEmitError!void {
    switch (value) {
        .array => |array| for (array.items) |item| try validateSchemaValue(item),
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn validateEnumValues(value: std.json.Value, expected_kind: []const u8) TypeEmitError!void {
    switch (value) {
        .array => |array| {
            if (array.items.len == 0) return TypeEmitError.UnsupportedSchema;
            for (array.items) |item| try validateConstValue(item, expected_kind);
        },
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn validateConstValue(value: std.json.Value, expected_kind: []const u8) TypeEmitError!void {
    if (std.mem.eql(u8, expected_kind, "string")) {
        if (value != .string) return TypeEmitError.UnsupportedSchema;
        return;
    }
    if (std.mem.eql(u8, expected_kind, "number")) {
        switch (value) {
            .integer, .float => return,
            else => return TypeEmitError.UnsupportedSchema,
        }
    }
    if (std.mem.eql(u8, expected_kind, "boolean")) {
        if (value != .bool) return TypeEmitError.UnsupportedSchema;
        return;
    }
    return TypeEmitError.UnsupportedSchema;
}

fn validateLiteralValue(value: std.json.Value) TypeEmitError!void {
    switch (value) {
        .string, .integer, .float, .bool => {},
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn emitSchemaType(writer: anytype, allocator: std.mem.Allocator, schema_json: []const u8, indent: usize) !void {
    var parsed = try parsedSchema(allocator, schema_json);
    defer parsed.deinit();
    try emitSchemaValue(writer, parsed.value, indent);
}

fn emitSchemaValue(writer: anytype, value: std.json.Value, indent: usize) anyerror!void {
    switch (value) {
        .object => |obj| {
            if (obj.get("const")) |const_val| {
                try emitLiteral(writer, const_val);
                return;
            }

            const type_val = obj.get("type") orelse return TypeEmitError.UnsupportedSchema;
            if (type_val != .string) return TypeEmitError.UnsupportedSchema;
            const kind = type_val.string;

            if (std.mem.eql(u8, kind, "string") or std.mem.eql(u8, kind, "number") or std.mem.eql(u8, kind, "boolean")) {
                if (obj.get("enum")) |enum_val| {
                    try emitEnum(writer, enum_val);
                } else if (obj.get("const")) |const_val| {
                    try emitLiteral(writer, const_val);
                } else {
                    try writer.writeAll(kind);
                }
                return;
            }

            if (std.mem.eql(u8, kind, "object")) {
                try emitObject(writer, obj, indent);
                return;
            }

            if (std.mem.eql(u8, kind, "array")) {
                if (obj.get("prefixItems")) |prefix_items| {
                    try emitTuple(writer, prefix_items, indent);
                } else {
                    const items = obj.get("items") orelse return TypeEmitError.UnsupportedSchema;
                    try writer.writeByte('(');
                    try emitSchemaValue(writer, items, indent);
                    try writer.writeAll(")[]");
                }
                return;
            }

            return TypeEmitError.UnsupportedSchema;
        },
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn emitEnum(writer: anytype, value: std.json.Value) !void {
    switch (value) {
        .array => |array| {
            for (array.items, 0..) |item, idx| {
                if (idx > 0) try writer.writeAll(" | ");
                try emitLiteral(writer, item);
            }
        },
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn emitLiteral(writer: anytype, value: std.json.Value) !void {
    switch (value) {
        .string => |s| try writeTsString(writer, s),
        .integer => |n| try writer.print("{d}", .{n}),
        .float => |n| try writer.print("{d}", .{n}),
        .bool => |b| try writer.writeAll(if (b) "true" else "false"),
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn emitObject(writer: anytype, obj: std.json.ObjectMap, indent: usize) !void {
    const props_val = obj.get("properties");
    if (props_val == null) {
        try writer.writeAll("Record<string, never>");
        return;
    }
    if (props_val.? != .object) return TypeEmitError.UnsupportedSchema;
    const props = props_val.?.object;

    try writer.writeAll("{\n");
    var it = props.iterator();
    while (it.next()) |entry| {
        try writeIndent(writer, indent + 2);
        try writePropertyName(writer, entry.key_ptr.*);
        if (!isRequiredField(obj, entry.key_ptr.*)) try writer.writeByte('?');
        try writer.writeAll(": ");
        try emitSchemaValue(writer, entry.value_ptr.*, indent + 2);
        try writer.writeAll(";\n");
    }
    try writeIndent(writer, indent);
    try writer.writeByte('}');
}

fn isRequiredField(obj: std.json.ObjectMap, field_name: []const u8) bool {
    const required_val = obj.get("required") orelse return false;
    return switch (required_val) {
        .array => |array| blk: {
            for (array.items) |item| {
                if (item == .string and std.mem.eql(u8, item.string, field_name)) break :blk true;
            }
            break :blk false;
        },
        else => false,
    };
}

fn emitTuple(writer: anytype, value: std.json.Value, indent: usize) !void {
    switch (value) {
        .array => |array| {
            try writer.writeByte('[');
            for (array.items, 0..) |item, idx| {
                if (idx > 0) try writer.writeAll(", ");
                try emitSchemaValue(writer, item, indent);
            }
            try writer.writeByte(']');
        },
        else => return TypeEmitError.UnsupportedSchema,
    }
}

fn writeMethodArgs(
    writer: anytype,
    route: ApiRouteInfo,
    request_type_name: ?[]const u8,
) !void {
    const has_params = route.path_params.items.len > 0;
    const has_query = route.query_params.items.len > 0;
    const has_body = request_type_name != null;
    if (!has_params and !has_query and !has_body) {
        try writer.writeAll("args: RequestOptions = {}");
        return;
    }

    try writer.writeAll("args: { ");
    if (has_params) {
        try writer.writeAll("params: ");
        try writeParamsType(writer, route.path_params.items);
        try writer.writeAll("; ");
    }
    if (has_query) {
        try writer.writeAll("query?: ");
        try writeQueryType(writer, route.query_params.items);
        try writer.writeAll("; ");
    }
    if (has_body) {
        try writer.writeAll("body: ");
        try writer.writeAll(request_type_name.?);
        try writer.writeAll("; ");
    }
    try writer.writeAll("headers?: HeadersInit; signal?: AbortSignal }");
}

fn writeParamsType(writer: anytype, params: []const ApiParamInfo) !void {
    try writer.writeAll("{ ");
    for (params, 0..) |param, idx| {
        if (idx > 0) try writer.writeAll("; ");
        try writePropertyName(writer, param.name);
        try writer.writeAll(": string");
    }
    try writer.writeAll(" }");
}

fn writeQueryType(writer: anytype, params: []const ApiParamInfo) !void {
    try writer.writeAll("{ ");
    for (params, 0..) |param, idx| {
        if (idx > 0) try writer.writeAll("; ");
        try writePropertyName(writer, param.name);
        if (!param.required) try writer.writeByte('?');
        try writer.writeAll(": ");
        try writer.writeAll(tsTypeForParamSchema(param.schema_json));
    }
    try writer.writeAll(" }");
}

fn tsTypeForParamSchema(schema_json: []const u8) []const u8 {
    var parsed = std.json.parseFromSlice(std.json.Value, std.heap.page_allocator, schema_json, .{}) catch return "string";
    defer parsed.deinit();
    if (parsed.value != .object) return "string";
    const type_val = parsed.value.object.get("type") orelse return "string";
    if (type_val != .string) return "string";
    if (std.mem.eql(u8, type_val.string, "number") or std.mem.eql(u8, type_val.string, "integer")) return "number";
    if (std.mem.eql(u8, type_val.string, "boolean")) return "boolean";
    return "string";
}

fn writeRequestPath(writer: anytype, route: ApiRouteInfo) !void {
    if (route.query_params.items.len > 0) {
        try writer.writeAll("appendQueryString(");
        try writePathTemplate(writer, route);
        try writer.writeAll(", input.query)");
        return;
    }
    try writePathTemplate(writer, route);
}

fn writePathTemplate(writer: anytype, route: ApiRouteInfo) !void {
    try writer.writeByte('`');
    var i: usize = 0;
    while (i < route.path.len) : (i += 1) {
        if (route.path[i] == ':') {
            const start = i + 1;
            var end = start;
            while (end < route.path.len and route.path[end] != '/') : (end += 1) {}
            const name = route.path[start..end];
            try writer.writeAll("${encodeURIComponent(input.params.");
            try writer.writeAll(name);
            try writer.writeAll(")}");
            i = end - 1;
            continue;
        }
        switch (route.path[i]) {
            '`' => try writer.writeAll("\\`"),
            '$' => try writer.writeAll("\\$"),
            '\\' => try writer.writeAll("\\\\"),
            else => try writer.writeByte(route.path[i]),
        }
    }
    try writer.writeByte('`');
}

fn writeIndent(writer: anytype, indent: usize) !void {
    var i: usize = 0;
    while (i < indent) : (i += 1) try writer.writeByte(' ');
}

fn writePropertyName(writer: anytype, name: []const u8) !void {
    if (isValidIdentifier(name)) {
        try writer.writeAll(name);
    } else {
        try writeTsString(writer, name);
    }
}

fn writeTsString(writer: anytype, value: []const u8) !void {
    try writer.writeByte('"');
    for (value) |c| {
        switch (c) {
            '\\' => try writer.writeAll("\\\\"),
            '"' => try writer.writeAll("\\\""),
            '\n' => try writer.writeAll("\\n"),
            '\r' => try writer.writeAll("\\r"),
            '\t' => try writer.writeAll("\\t"),
            else => try writer.writeByte(c),
        }
    }
    try writer.writeByte('"');
}

fn methodNameForRoute(allocator: std.mem.Allocator, route: ApiRouteInfo) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    const lower_method = try lowerCaseOwned(allocator, route.method);
    defer allocator.free(lower_method);
    try out.appendSlice(allocator, lower_method);
    if (std.mem.eql(u8, route.path, "/")) {
        try out.appendSlice(allocator, "Root");
        return out.toOwnedSlice(allocator);
    }

    var start: usize = 0;
    while (start < route.path.len) {
        while (start < route.path.len and route.path[start] == '/') : (start += 1) {}
        if (start >= route.path.len) break;
        var end = start;
        while (end < route.path.len and route.path[end] != '/') : (end += 1) {}
        const segment = route.path[start..end];
        const cleaned = if (segment.len > 0 and segment[0] == ':') segment[1..] else segment;
        const titled = try titleCaseSegment(allocator, cleaned);
        defer allocator.free(titled);
        try out.appendSlice(allocator, titled);
        start = end;
    }
    return out.toOwnedSlice(allocator);
}

fn sanitizeTypeName(allocator: std.mem.Allocator, raw: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    var capitalize_next = true;
    for (raw) |c| {
        if (std.ascii.isAlphanumeric(c)) {
            if (capitalize_next) {
                try out.append(allocator, std.ascii.toUpper(c));
                capitalize_next = false;
            } else {
                try out.append(allocator, c);
            }
        } else {
            capitalize_next = true;
        }
    }
    if (out.items.len == 0) {
        try out.appendSlice(allocator, "ApiType");
    }
    return out.toOwnedSlice(allocator);
}

fn lowerCaseOwned(allocator: std.mem.Allocator, input: []const u8) ![]u8 {
    var out = try allocator.alloc(u8, input.len);
    for (input, 0..) |c, idx| out[idx] = std.ascii.toLower(c);
    return out;
}

fn titleCaseSegment(allocator: std.mem.Allocator, input: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    var capitalize_next = true;
    for (input) |c| {
        if (std.ascii.isAlphanumeric(c)) {
            if (capitalize_next) {
                try out.append(allocator, std.ascii.toUpper(c));
                capitalize_next = false;
            } else {
                try out.append(allocator, std.ascii.toLower(c));
            }
        } else {
            capitalize_next = true;
        }
    }
    return out.toOwnedSlice(allocator);
}

fn uniquifyOwnedName(
    allocator: std.mem.Allocator,
    used_names: *std.ArrayList([]const u8),
    name: *[]u8,
) !void {
    if (!containsString(used_names.items, name.*)) {
        try used_names.append(allocator, try allocator.dupe(u8, name.*));
        return;
    }

    const base = try allocator.dupe(u8, name.*);
    defer allocator.free(base);
    allocator.free(name.*);

    var counter: usize = 2;
    while (true) : (counter += 1) {
        const candidate = try std.fmt.allocPrint(allocator, "{s}{d}", .{ base, counter });
        if (!containsString(used_names.items, candidate)) {
            name.* = candidate;
            try used_names.append(allocator, try allocator.dupe(u8, candidate));
            return;
        }
        allocator.free(candidate);
    }
}

const containsString = handler_contract.containsString;

fn isValidIdentifier(name: []const u8) bool {
    if (name.len == 0) return false;
    if (!isIdentifierStart(name[0])) return false;
    for (name[1..]) |c| {
        if (!isIdentifierContinue(c)) return false;
    }
    return !isReservedWord(name);
}

fn isIdentifierStart(c: u8) bool {
    return std.ascii.isAlphabetic(c) or c == '_' or c == '$';
}

fn isIdentifierContinue(c: u8) bool {
    return isIdentifierStart(c) or std.ascii.isDigit(c);
}

fn isReservedWord(name: []const u8) bool {
    const reserved = [_][]const u8{
        "break",   "case", "catch",    "class", "const",  "continue", "default",
        "delete",  "do",   "else",     "enum",  "export", "extends",  "false",
        "finally", "for",  "function", "if",    "import", "in",       "instanceof",
        "new",     "null", "return",   "super", "switch", "this",     "throw",
        "true",    "try",  "typeof",   "var",   "void",   "while",    "with",
    };
    for (reserved) |word| {
        if (std.mem.eql(u8, name, word)) return true;
    }
    return false;
}

test "writeTypeScriptClient renders typed route and skipped operation" {
    const allocator = std.testing.allocator;

    var schemas: std.ArrayList(ApiSchemaInfo) = .empty;
    try schemas.append(allocator, .{
        .name = try allocator.dupe(u8, "todo.create"),
        .schema_json = try allocator.dupe(u8, "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\"},\"active\":{\"type\":\"boolean\"}},\"required\":[\"name\"]}"),
    });
    try schemas.append(allocator, .{
        .name = try allocator.dupe(u8, "todo"),
        .schema_json = try allocator.dupe(u8, "{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"active\":{\"type\":\"boolean\"}},\"required\":[\"id\",\"active\"]}"),
    });

    var route_requests: std.ArrayList([]const u8) = .empty;
    try route_requests.append(allocator, try allocator.dupe(u8, "todo.create"));
    var path_params: std.ArrayList(ApiParamInfo) = .empty;
    try path_params.append(allocator, .{
        .name = try allocator.dupe(u8, "id"),
        .location = "path",
        .required = true,
        .schema_json = try allocator.dupe(u8, "{\"type\":\"string\"}"),
    });
    var query_params: std.ArrayList(ApiParamInfo) = .empty;
    try query_params.append(allocator, .{
        .name = try allocator.dupe(u8, "verbose"),
        .location = "query",
        .required = false,
        .schema_json = try allocator.dupe(u8, "{\"type\":\"string\"}"),
    });

    var routes: std.ArrayList(ApiRouteInfo) = .empty;
    try routes.append(allocator, .{
        .method = try allocator.dupe(u8, "POST"),
        .path = try allocator.dupe(u8, "/todos/:id"),
        .request_schema_refs = route_requests,
        .request_schema_dynamic = false,
        .requires_bearer = true,
        .requires_jwt = false,
        .path_params = path_params,
        .query_params = query_params,
        .response_status = 201,
        .response_content_type = try allocator.dupe(u8, "application/json"),
        .response_schema_ref = try allocator.dupe(u8, "todo"),
        .response_schema_dynamic = false,
    });

    try routes.append(allocator, .{
        .method = try allocator.dupe(u8, "GET"),
        .path = try allocator.dupe(u8, "/metrics"),
        .request_schema_refs = .empty,
        .request_schema_dynamic = false,
        .requires_bearer = false,
        .requires_jwt = false,
        .response_status = 200,
        .response_content_type = try allocator.dupe(u8, "text/plain; charset=utf-8"),
        .response_schema_dynamic = false,
    });

    var contract = HandlerContract{
        .handler = .{ .path = try allocator.dupe(u8, "examples/api.ts"), .line = 1, .column = 1 },
        .routes = .empty,
        .modules = .empty,
        .functions = .empty,
        .env = .{ .literal = .empty, .dynamic = false },
        .egress = .{ .endpoints = .empty, .dynamic = false },
        .cache = .{ .namespaces = .empty, .dynamic = false },
        .sql = handler_contract.emptySqlInfo(),
        .durable = .{
            .used = false,
            .keys = .{ .literal = .empty, .dynamic = false },
            .steps = .empty,
        },
        .scope = .{
            .used = false,
            .names = .empty,
            .dynamic = false,
            .max_depth = 0,
        },
        .api = .{
            .schemas = schemas,
            .requests = .{ .schema_refs = .empty, .dynamic = false },
            .auth = .{ .bearer = true, .jwt = false },
            .routes = routes,
            .schemas_dynamic = false,
            .routes_dynamic = false,
        },
        .verification = null,
        .aot = null,
    };
    defer contract.deinit(allocator);

    var output: std.ArrayList(u8) = .empty;
    defer output.deinit(allocator);
    var aw: std.Io.Writer.Allocating = .fromArrayList(allocator, &output);
    try writeTypeScriptClient(&aw.writer, allocator, &contract, .{});
    output = aw.toArrayList();

    try std.testing.expect(std.mem.indexOf(u8, output.items, "export type TodoCreate = {") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "export type Todo = {") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "async postTodosId(") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "params: { id: string }") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "query?: { verbose?: string }") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "body: TodoCreate") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "TypedResponse<Todo>") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "requestRaw") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "appendQueryString(`") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "response is not proven JSON") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "requires bearer authentication") != null);
}

test "writeTypeScriptClient emits inline response alias" {
    const allocator = std.testing.allocator;

    var routes: std.ArrayList(ApiRouteInfo) = .empty;
    try routes.append(allocator, .{
        .method = try allocator.dupe(u8, "GET"),
        .path = try allocator.dupe(u8, "/health"),
        .request_schema_refs = .empty,
        .request_schema_dynamic = false,
        .requires_bearer = false,
        .requires_jwt = false,
        .response_status = 200,
        .response_content_type = try allocator.dupe(u8, "application/json"),
        .response_schema_json = try allocator.dupe(u8, "{\"type\":\"object\",\"properties\":{\"ok\":{\"type\":\"boolean\"}},\"required\":[\"ok\"]}"),
        .response_schema_dynamic = false,
    });

    var contract = HandlerContract{
        .handler = .{ .path = try allocator.dupe(u8, "health.ts"), .line = 1, .column = 1 },
        .routes = .empty,
        .modules = .empty,
        .functions = .empty,
        .env = .{ .literal = .empty, .dynamic = false },
        .egress = .{ .endpoints = .empty, .dynamic = false },
        .cache = .{ .namespaces = .empty, .dynamic = false },
        .sql = handler_contract.emptySqlInfo(),
        .durable = .{
            .used = false,
            .keys = .{ .literal = .empty, .dynamic = false },
            .steps = .empty,
        },
        .scope = .{
            .used = false,
            .names = .empty,
            .dynamic = false,
            .max_depth = 0,
        },
        .api = .{
            .schemas = .empty,
            .requests = .{ .schema_refs = .empty, .dynamic = false },
            .auth = .{ .bearer = false, .jwt = false },
            .routes = routes,
            .schemas_dynamic = false,
            .routes_dynamic = false,
        },
        .verification = null,
        .aot = null,
    };
    defer contract.deinit(allocator);

    var output: std.ArrayList(u8) = .empty;
    defer output.deinit(allocator);
    var aw: std.Io.Writer.Allocating = .fromArrayList(allocator, &output);
    try writeTypeScriptClient(&aw.writer, allocator, &contract, .{});
    output = aw.toArrayList();

    try std.testing.expect(std.mem.indexOf(u8, output.items, "export type GetHealthResponse = {") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "async getHealth(") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "TypedResponse<GetHealthResponse>") != null);
}

test "writeTypeScriptClient emits discriminated union for multi-response route" {
    const allocator = std.testing.allocator;

    // Named schema for the 200 response.
    var schemas: std.ArrayList(ApiSchemaInfo) = .empty;
    try schemas.append(allocator, .{
        .name = try allocator.dupe(u8, "user"),
        .schema_json = try allocator.dupe(u8, "{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\"]}"),
    });

    // Route with two responses: 200 via schema_ref, 404 via inline schema_json.
    var responses: std.ArrayList(handler_contract.ApiResponseInfo) = .empty;
    try responses.append(allocator, .{
        .status = 200,
        .content_type = try allocator.dupe(u8, "application/json"),
        .schema = .{ .ref = try allocator.dupe(u8, "user") },
    });
    try responses.append(allocator, .{
        .status = 404,
        .content_type = try allocator.dupe(u8, "application/json"),
        .schema = .{ .inline_json = try allocator.dupe(u8, "{\"type\":\"object\",\"properties\":{\"error\":{\"type\":\"string\"}},\"required\":[\"error\"]}") },
    });

    var routes: std.ArrayList(ApiRouteInfo) = .empty;
    try routes.append(allocator, .{
        .method = try allocator.dupe(u8, "GET"),
        .path = try allocator.dupe(u8, "/users/:id"),
        .request_schema_refs = .empty,
        .request_schema_dynamic = false,
        .requires_bearer = false,
        .requires_jwt = false,
        .responses = responses,
        .responses_dynamic = false,
    });

    var contract = HandlerContract{
        .handler = .{ .path = try allocator.dupe(u8, "users.ts"), .line = 1, .column = 1 },
        .routes = .empty,
        .modules = .empty,
        .functions = .empty,
        .env = .{ .literal = .empty, .dynamic = false },
        .egress = .{ .endpoints = .empty, .dynamic = false },
        .cache = .{ .namespaces = .empty, .dynamic = false },
        .sql = handler_contract.emptySqlInfo(),
        .durable = .{
            .used = false,
            .keys = .{ .literal = .empty, .dynamic = false },
            .steps = .empty,
        },
        .scope = .{
            .used = false,
            .names = .empty,
            .dynamic = false,
            .max_depth = 0,
        },
        .api = .{
            .schemas = schemas,
            .requests = .{ .schema_refs = .empty, .dynamic = false },
            .auth = .{ .bearer = false, .jwt = false },
            .routes = routes,
            .schemas_dynamic = false,
            .routes_dynamic = false,
        },
        .verification = null,
        .aot = null,
    };
    defer contract.deinit(allocator);

    var output: std.ArrayList(u8) = .empty;
    defer output.deinit(allocator);
    var aw: std.Io.Writer.Allocating = .fromArrayList(allocator, &output);
    try writeTypeScriptClient(&aw.writer, allocator, &contract, .{});
    output = aw.toArrayList();

    // Named schema type emitted.
    try std.testing.expect(std.mem.indexOf(u8, output.items, "export type User = {") != null);
    // Inline type for the 404 arm emitted.
    try std.testing.expect(std.mem.indexOf(u8, output.items, "export type GetUsersId404Response = {") != null);
    // Method generated (not in skippedOperations).
    try std.testing.expect(std.mem.indexOf(u8, output.items, "async getUsersId(") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "multiple responses are not supported") == null);
    // Discriminated union return type contains both arms.
    try std.testing.expect(std.mem.indexOf(u8, output.items, "status: 200; data: User") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.items, "status: 404; data: GetUsersId404Response") != null);
    // Body uses the as-any cast pattern.
    try std.testing.expect(std.mem.indexOf(u8, output.items, "} as any;") != null);
}
