//! Handler sources generated by crossing the predicates the synthesizers branch
//! on.
//!
//! The route and env synthesizers each read a handful of facts off the source
//! and take a different path per combination, and every one of those paths has
//! been exercised by four hand-written fixtures. That is the blind spot the
//! file-destroying edit came from: a synthesizer is only ever seen against the
//! shapes somebody thought to write down.
//!
//! A grammar is the right form here for one reason. Its productions are not
//! guesses about what a handler might look like - they are the branch conditions
//! in the code under test, read off the source and listed. The oracle is the real
//! veto, so a generated variant that breaks a synthesizer fails loudly instead of
//! needing a second model of which sources produce which output.
//!
//! What is deliberately NOT here: a free program grammar. Generating arbitrary
//! handlers would need its own model of which programs trip which diagnostics,
//! which is a second implementation of the checker to disagree with the first.

const std = @import("std");
const TextBuffer = @import("../text_buffer.zig").TextBuffer;

/// The facts `synthesizeRoute` reads off a source (playbook.zig, at the top of
/// that function). Each field here is one of those reads, so the cross product
/// below is its branch space rather than a sample of it.
pub const RouteVariant = struct {
    has_router: bool,
    has_routes: bool,
    has_spec_import: bool,
    has_guardrails_alias: bool,
};

/// Every combination, in a stable order. Sixteen, which is small enough to run
/// the real veto over and large enough that no single fixture stands in for a
/// branch.
pub const route_variants = build: {
    var out: [16]RouteVariant = undefined;
    var i: usize = 0;
    for ([_]bool{ false, true }) |router| {
        for ([_]bool{ false, true }) |routes| {
            for ([_]bool{ false, true }) |spec_import| {
                for ([_]bool{ false, true }) |alias| {
                    out[i] = .{
                        .has_router = router,
                        .has_routes = routes,
                        .has_spec_import = spec_import,
                        .has_guardrails_alias = alias,
                    };
                    i += 1;
                }
            }
        }
    }
    break :build out;
};

/// The facts `synthesizeEnvFeature` reads. `existing_read` is separate from the
/// import because the two are independent in the source and the synthesizer
/// answers differently to each: a matching read short-circuits to
/// `.existing_read` whether or not the import is present.
pub const EnvVariant = struct {
    has_env_import: bool,
    has_existing_read: bool,
    /// A handler declaration the body scan can find. False produces a source the
    /// synthesizer must refuse rather than edit.
    has_handler_body: bool,
};

pub const env_variants = build: {
    var out: [8]EnvVariant = undefined;
    var i: usize = 0;
    for ([_]bool{ false, true }) |import| {
        for ([_]bool{ false, true }) |read| {
            for ([_]bool{ false, true }) |body| {
                out[i] = .{ .has_env_import = import, .has_existing_read = read, .has_handler_body = body };
                i += 1;
            }
        }
    }
    break :build out;
};

/// The variable the env sources read, and the one the gate asks the synthesizer
/// to add. Shared so a variant's `has_existing_read` means what the synthesizer
/// will conclude.
pub const env_variable = "APP_NAME";

pub fn renderRouteSource(allocator: std.mem.Allocator, v: RouteVariant) ![]u8 {
    var buf = TextBuffer.init(allocator);
    defer buf.deinit();
    const w = buf.writer();

    if (v.has_spec_import) try w.writeAll("import type { Spec } from \"zttp:types\";\n");
    if (v.has_router) try w.writeAll("import { routerMatch } from \"zttp:router\";\n");
    if (v.has_spec_import or v.has_router) try w.writeAll("\n");

    if (v.has_guardrails_alias) {
        try w.writeAll(
            \\type Guardrails = Spec<
            \\    | "deterministic"
            \\    | "idempotent"
            \\    | "no_secret_leakage"
            \\    | "injection_safe"
            \\>;
            \\
            \\
        );
    }

    if (v.has_routes) {
        try w.writeAll(
            \\const routes = {
            \\    "GET /existing": handleGetExisting,
            \\};
            \\
            \\function handleGetExisting(req: Request): Response {
            \\    return Response.json({ existing: true });
            \\}
            \\
            \\
        );
    }

    try w.writeAll(
        \\function handler(req: Request): Response {
        \\    return Response.json({ ok: true });
        \\}
        \\
    );
    return try buf.toOwnedSlice();
}

pub fn renderEnvSource(allocator: std.mem.Allocator, v: EnvVariant) ![]u8 {
    var buf = TextBuffer.init(allocator);
    defer buf.deinit();
    const w = buf.writer();

    if (v.has_env_import) try w.writeAll("import { env } from \"zttp:env\";\n\n");

    if (!v.has_handler_body) {
        // No handler declaration for the body scan to find. The synthesizer must
        // refuse this rather than splice into whatever it hits first.
        try w.writeAll("const unrelated = 1;\n");
        return try buf.toOwnedSlice();
    }

    try w.writeAll("function handler(req: Request): Response {\n");
    if (v.has_existing_read) {
        try w.print("    env(\"{s}\");\n", .{env_variable});
    }
    try w.writeAll("    return Response.json({ ok: true });\n}\n");
    return try buf.toOwnedSlice();
}
